# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch
# (/etc/nixos is this folder, /home/frank/.config/nixos.)
{ inputs, lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Profile: Office.
  hardware.sane.enable = true;
  services.avahi.enable = true;
  services.avahi.nssmdns4 = true;
  services.printing.enable = true;

  # Desktop: GNOME.
  services.desktopManager.gnome.enable = true;

  # Login manager.
  services.displayManager.gdm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [
    (pkgs.makeDesktopItem {
      name = "webapp-youtube";
      desktopName = "YouTube";
      comment = "Videos";
      exec = (lib.getExe pkgs.chromium + " --app=https://youtube.com/");
      categories = [ "Network" ];
      icon = "${inputs.configurator}/data/webapps/youtube.png";
    })
  ];
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  programs.dconf.enable = true;
  programs.dconf.profiles.user.databases = [
    {
      settings = {
        "org/gnome/desktop/wm/keybindings" = {
          close = [ "<Super>q" ];
        };
        "org/gnome/mutter" = {
          overlay-key = "Super_R";
        };
        "org/gnome/settings-daemon/plugins/media-keys" = {
          custom-keybindings = [
            "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/configurator0/"
            "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/configurator1/"
          ];
        };
        "org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/configurator0" = {
          name = "Launch gnome-console";
          command = lib.getExe pkgs.gnome-console;
          binding = "<Super>Return";
        };
        "org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/configurator1" = {
          name = "Open youtube";
          command = (lib.getExe pkgs.chromium + " --app=https://youtube.com/");
          binding = "<Super><Shift>y";
        };
      };
    }
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.frank = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "gnome";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/frank/.config/nixos" ];
  environment.etc.nixos.source = "/home/frank/.config/nixos";
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
