# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Apply changes with: sudo nixos-rebuild switch
# (/etc/nixos is this folder, /home/frank/.config/nixos.)
{
  description = "NixOS configuration of gnome";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    configurator = {
      url = "github:nix-composer/configurator";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
  outputs = { nixpkgs, ... }@inputs: {
    nixosConfigurations.gnome = nixpkgs.lib.nixosSystem {
      specialArgs = { inherit inputs; };
      modules = [
        inputs.disko.nixosModules.disko
        ./disko.nix
        ./hardware.nix
        ./configuration.nix
      ];
    };
  };
}
