# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/nia/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = "UTC";

  # Desktop: niri.
  programs.niri.enable = true;

  # Login manager.
  services.displayManager.ly.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [ pkgs.foot pkgs.fuzzel ];
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  environment.etc."niri/config.kdl".text = lib.concatLines [
    ("include \"" + pkgs.runCommand "niri-default-config.kdl" { } "cp ${pkgs.niri.src}/resources/default-config.kdl $out" + "\"")
    "binds {"
    ("    Super+d { spawn-sh " + builtins.toJSON ("fuzzel") + "; }")
    ("    Super+Return { spawn-sh " + builtins.toJSON (lib.getExe pkgs.foot) + "; }")
    ("    Super+Shift+e { spawn-sh " + builtins.toJSON ("notify-send \"hi there\"") + "; }")
    "}"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.nia = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "scroller";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/nia/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
