# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/alex/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone.
  i18n.defaultLocale = "nl_NL.UTF-8";
  services.xserver.xkb.layout = "us";
  services.xserver.xkb.variant = "intl";
  console.useXkbConfig = true;
  time.timeZone = "Europe/Amsterdam";

  # Profile: Office.
  hardware.sane.enable = true;
  services.avahi.enable = true;
  services.avahi.nssmdns4 = true;
  services.printing.enable = true;

  # Desktop: GNOME.
  services.desktopManager.gnome.enable = true;

  # Login manager.
  services.displayManager.gdm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [
    pkgs.libreoffice
    pkgs.thunderbird
    pkgs.firefox
    (pkgs.makeDesktopItem {
      name = "webapp-gmail";
      desktopName = "Gmail";
      comment = "Email";
      exec = (lib.getExe pkgs.chromium + " --app=https://mail.google.com");
      categories = [ "Network" ];
    })
    (pkgs.makeDesktopItem {
      name = "webapp-google-calendar";
      desktopName = "Google Calendar";
      comment = "Calendar";
      exec = (lib.getExe pkgs.chromium + " --app=https://calendar.google.com");
      categories = [ "Network" ];
    })
  ];
  nixpkgs.config.allowUnfree = true;

  # Development. Start a project from a template with:
  #   nix flake new -t dev#python ~/Projects/my-python-project
  #   nix flake new -t dev#rust ~/Projects/my-rust-project
  programs.direnv.enable = true;
  nix.registry.dev.to = {
    type = "github";
    owner = "nix-templates";
    repo = "dev";
  };
  virtualisation.docker.enable = true;
  virtualisation.oci-containers.backend = "docker";
  virtualisation.oci-containers.containers.postgres = {
    image = "postgres:18";
    ports = [ "127.0.0.1:5432:5432" ];
    environment = {
      POSTGRES_HOST_AUTH_METHOD = "trust";
    };
    volumes = [ "postgres:/var/lib/postgresql" ];
  };
  virtualisation.oci-containers.containers.redis = {
    image = "redis:7";
    ports = [ "127.0.0.1:6379:6379" ];
    volumes = [ "redis:/data" ];
  };

  # Shell.
  programs.fish.enable = true;
  users.defaultUserShell = pkgs.fish;

  # Keybinds, on top of the desktop's defaults.
  programs.dconf.enable = true;
  programs.dconf.profiles.user.databases = [
    {
      settings = {
        "org/gnome/desktop/wm/keybindings" = {
          close = lib.gvariant.mkEmptyArray lib.gvariant.type.string;
          minimize = lib.gvariant.mkEmptyArray lib.gvariant.type.string;
        };
        "org/gnome/settings-daemon/plugins/media-keys" = {
          custom-keybindings = [
            "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/configurator0/"
            "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/configurator1/"
            "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/configurator2/"
            "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/configurator3/"
          ];
        };
        "org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/configurator0" = {
          name = "Launch nautilus";
          command = lib.getExe pkgs.nautilus;
          binding = "<Super>e";
        };
        "org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/configurator1" = {
          name = "Run gnome-text-editor";
          command = "gnome-text-editor";
          binding = "<Super>h";
        };
        "org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/configurator2" = {
          name = "Launch gnome-console";
          command = lib.getExe pkgs.gnome-console;
          binding = "<Super>Return";
        };
        "org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/configurator3" = {
          name = "Open google-calendar";
          command = (lib.getExe pkgs.chromium + " --app=https://calendar.google.com");
          binding = "<Super><Shift>c";
        };
      };
    }
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.alex = {
    isNormalUser = true;
    description = "Alex";
    extraGroups = [ "wheel" "networkmanager" "video" "docker" ];
  };
  users.users.sam = {
    isNormalUser = true;
    description = "Sam";
    extraGroups = [ "networkmanager" "video" "docker" ];
  };

  # System.
  networking.hostName = "office-pc";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/alex/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
