# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
{ ... }:
{
  # Disk layout (disko): btrfs with subvolumes on LUKS, legacy BIOS boot.
  disko.devices.disk.main = {
    type = "disk";
    device = "/dev/vdb";
    content = {
      type = "gpt";
      partitions = {
        bios = {
          size = "1M";
          type = "EF02";
        };
        boot = {
          size = "1G";
          content = {
            type = "filesystem";
            format = "ext4";
            extraArgs = [ "-O" "^metadata_csum_seed,^orphan_file,^64bit" ];
            mountpoint = "/boot";
          };
        };
        root = {
          size = "100%";
          content = {
            type = "luks";
            name = "cryptroot";
            passwordFile = "/tmp/configurator-luks.key";
            settings.allowDiscards = true;
            content = {
              type = "btrfs";
              extraArgs = [ "-f" ];
              subvolumes = {
                "@" = {
                  mountpoint = "/";
                  mountOptions = [ "compress=zstd" "noatime" ];
                };
                "@home" = {
                  mountpoint = "/home";
                  mountOptions = [ "compress=zstd" "noatime" ];
                };
                "@nix" = {
                  mountpoint = "/nix";
                  mountOptions = [ "compress=zstd" "noatime" ];
                };
                "@snapshots" = {
                  mountpoint = "/.snapshots";
                  mountOptions = [ "compress=zstd" "noatime" ];
                };
                "@swap" = {
                  mountpoint = "/.swapvol";
                  swap.swapfile.size = "1G";
                };
              };
            };
          };
        };
      };
    };
  };
}
