# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/kim/.config/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: JWM.
  services.xserver.enable = true;
  services.xserver.windowManager.jwm.enable = true;

  # Login manager.
  services.xserver.displayManager.lightdm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  environment.etc."jwm/jwmrc".text = lib.concatLines [
    "<?xml version=\"1.0\"?>"
    "<!-- Written by the Configurator from your NixOS configuration (keybinds"
    "     there); ~/.jwmrc includes it. -->"
    "<JWM>"
    "  <Include>${pkgs.jwm}/etc/system.jwmrc</Include>"
    "  <Key mask=\"A\" key=\"F1\">exec:true</Key>"
    "  <Key mask=\"A\" key=\"F4\">exec:true</Key>"
    "  <Key mask=\"4\" key=\"F10\">close</Key>"
    "  <Key mask=\"4\" key=\"F9\">exec:touch /tmp/kb-added</Key>"
    "</JWM>"
  ];
  systemd.user.tmpfiles.rules = [
    "f %h/.jwmrc 0644 - - - <?xml version=\"1.0\"?>\\n<!-- Your JWM config. The Include loads JWM's defaults with the keybinds\\n     from your NixOS configuration; what you add after it wins. -->\\n<JWM>\\n  <Include>/etc/jwm/jwmrc</Include>\\n</JWM>\\n"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
