# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/pat/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone.
  i18n.defaultLocale = "en_GB.UTF-8";
  services.xserver.xkb.layout = "gb";
  console.useXkbConfig = true;
  time.timeZone = "Europe/London";

  # Desktop: evilwm.
  fonts.packages = ([ (pkgs.runCommand "x11-font-aliases" { } "mkdir -p $out/share/fonts/X11/misc && cp ${pkgs.font-alias}/share/fonts/X11/misc/fonts.alias $out/share/fonts/X11/misc && echo 0 > $out/share/fonts/X11/misc/fonts.dir") ]);
  services.xserver.enable = true;
  services.xserver.windowManager.evilwm.enable = true;

  # Login manager.
  services.xserver.displayManager.lightdm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [
    pkgs.feh
    pkgs.dunst
    pkgs.slock
    pkgs.pavucontrol
    pkgs.scrot
    pkgs.xclip
  ];
  nixpkgs.config.allowUnfree = true;

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.pat = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "evil";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/pat/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
