# Screenshots of every desktop in the registry, for the Desktop layer:
# each desktop boots in a VM, logs a user straight into its session and is
# photographed, so the images follow the desktops as nixpkgs updates them.
#
#   nix build .#desktop-screenshots                  # all: <id>.jpg each
#   nix build .#desktop-screenshots.perDesktop.gnome  # one: gnome.jpg
#
# The combined output skips desktops whose VM fails (the GUI falls back to
# artwork for those); each one's test log says why.
{
  pkgs,
  self,
  nixpkgs,
  inputs,
}:
let
  inherit (pkgs) lib;
  registry = lib.importJSON ../../data/desktops.json;
  user = "alice";

  # The registry's special values, as far as a screenshot needs them.
  resolve =
    pkgs: id: value:
    if builtins.isAttrs value && value ? "$context" then
      if value."$context" == "users" then [ user ] else throw "screenshots: ${id}: ${value."$context"}"
    else if builtins.isAttrs value && value ? "$path" then
      throw "screenshots: ${id}: $path needs the host flake"
    else if builtins.isAttrs value && value ? "$expr" then
      # Nix code, as the generated configuration.nix has it.
      import (builtins.toFile "${id}-expr.nix" "{ pkgs, lib }: ${value."$expr"}") { inherit pkgs lib; }
    else
      value;
  # The desktop's registry config, as a module.
  moduleConfig =
    d:
    { pkgs, ... }:
    lib.foldl' lib.recursiveUpdate { } (
      lib.mapAttrsToList (
        path: value: lib.setAttrByPath (lib.splitString "." path) (resolve pkgs d.id value)
      ) d.module.config
    );

  # The login manager each desktop pairs with, logging in by itself.
  loginManager =
    d:
    {
      gdm.services.displayManager.gdm.enable = true;
      sddm.services.displayManager.sddm = {
        enable = true;
        wayland.enable = lib.elem "wayland" d.sessions;
      };
      lightdm.services.xserver = {
        enable = true;
        displayManager.lightdm.enable = true;
      };
      cosmic-greeter.services.displayManager.cosmic-greeter.enable = true;
      ly.services.displayManager.ly.enable = true;
    }
    .${d.loginManager};

  # tmpfiles rules that put a copy of `source` at `path` in the user's home.
  homeFile = path: source: [
    "d /home/${user}/.config 0755 ${user} users -"
    "d /home/${user}/${builtins.dirOf path} 0755 ${user} users -"
    "C /home/${user}/${path} 0644 ${user} users - ${source}"
  ];

  # What a desktop needs to show itself as it does after setup, rather
  # than a first-run dialog or a VM limitation.
  extras = {
    gnome = pkgs: {
      environment.gnome.excludePackages = [ pkgs.gnome-tour ];
    };
    cosmic = pkgs: {
      environment.cosmic.excludePackages = [ pkgs.cosmic-initial-setup ];
      services.desktopManager.cosmic.showExcludedPkgsWarning = false;
    };
    # Hyprland's example config, so it doesn't warn about an
    # autogenerated one.
    hyprland = pkgs: {
      systemd.tmpfiles.rules = homeFile ".config/hypr/hyprland.lua" "${pkgs.hyprland}/share/hypr/hyprland.lua";
    };
    # niri refuses software rendering (Mesa's llvmpipe), which is all a VM
    # without a GPU has; for a picture it draws fine. Mesa's software EGL
    # device has no render node, so it gets the card's.
    niri = pkgs: {
      programs.niri.package = pkgs.niri.overrideAttrs (old: {
        postPatch = (old.postPatch or "") + ''
          substituteInPlace src/backend/tty.rs \
            --replace-fail '!egl_device.is_software(),' 'true,' \
            --replace-fail '.unwrap_or(node);' \
              '.or_else(|| node.node_with_type(NodeType::Render).and_then(Result::ok)).unwrap_or(node);'
        '';
        doCheck = false;
      });
    };
    # i3's default config, without its first-run config wizard.
    i3 = pkgs: {
      services.xserver.windowManager.i3.configFile = pkgs.runCommand "i3-config" { } ''
        grep -v i3-config-wizard ${pkgs.i3}/etc/i3/config > $out
      '';
    };
  };

  # A window manager shows little on its own: open a terminal in it, so the
  # picture shows how it frames windows.
  opensWindow = d: d.kind == "window-manager";
  wayland = d: !(lib.elem "x11" d.sessions);
  terminal =
    d:
    if wayland d then
      "export XDG_RUNTIME_DIR=/run/user/$(id -u); "
      + "export WAYLAND_DISPLAY=$(basename $(ls $XDG_RUNTIME_DIR/wayland-? | head -1)); "
      + "foot --hold fastfetch"
    else
      "DISPLAY=:0 xterm -geometry 100x30 -fa Monospace -fs 11 -hold -e fastfetch";

  screenshot =
    d:
    pkgs.testers.runNixOSTest {
      name = "screenshot-${d.id}";
      nodes.machine =
        { pkgs, ... }:
        {
          imports = [
            (moduleConfig d)
            (loginManager d)
            (extras.${d.id} or (_: { }) pkgs)
          ];
          users.users.${user} = {
            isNormalUser = true;
            password = "alice";
            extraGroups = [ "wheel" ];
          };
          # Into the desktop's first session (NixOS picks it when there's
          # no defaultSession): its own, e.g. "plasma" over "plasmax11".
          services.displayManager.autoLogin = {
            enable = true;
            inherit user;
          };
          virtualisation = {
            memorySize = 4096;
            cores = 4;
            resolution = {
              x = 1280;
              y = 800;
            };
            # A virtio GPU: Wayland compositors need DRM/KMS; rendered by
            # Mesa in software.
            qemu.options = [
              "-vga none"
              "-device virtio-gpu-pci,xres=1280,yres=800"
            ];
          };
          environment.sessionVariables = {
            WLR_RENDERER = "pixman";
            WLR_NO_HARDWARE_CURSORS = "1";
          };
          fonts.enableDefaultPackages = true;
          environment.systemPackages = lib.optionals (opensWindow d) [
            pkgs.fastfetch
            (if wayland d then pkgs.foot else pkgs.xterm)
          ];
        };
      # A desktop that doesn't come up leaves no screenshot instead of
      # failing, so the others still make it into the combined output.
      testScript = ''
        try:
            machine.wait_for_unit("display-manager.service")
            # The session's processes run as the user once it's logged in.
            machine.wait_until_succeeds("loginctl list-sessions --no-legend | grep -q ${user}", timeout=300)
            machine.wait_until_succeeds("test $(pgrep -u ${user} | wc -l) -gt 3", timeout=300)
            # Desktops draw their panels and wallpaper after the session starts.
            machine.sleep(30)
        ${lib.optionalString (opensWindow d) "    machine.execute(\"su - ${user} -c '${terminal d}' >/dev/null 2>&1 &\")"}
            machine.sleep(15)
            machine.screenshot("screen")
        except Exception as e:
            print(f"screenshot-${d.id}: no session, no screenshot: {e}")
      '';
    };

  # Omarchy isn't in nixpkgs: its screenshot needs the nix-desktops/omarchy
  # flake (see lib.omarchyTest in flake.nix for how its VM test gets it).
  # Until then the GUI draws its artwork.
  desktops = lib.filter (d: !(d.module ? flake)) registry.desktops;

  # Desktops that don't evaluate or build with this nixpkgs (`unavailable`
  # in the registry); they're left out of the combined output (their own
  # attribute still fails, to check whether they work again).
  broken = map (d: d.id) (lib.filter (d: d ? unavailable) registry.desktops);

  perDesktop = lib.listToAttrs (
    map (
      d:
      let
        test = screenshot d;
      in
      lib.nameValuePair d.id (
        pkgs.runCommand "screenshot-${d.id}"
          {
            nativeBuildInputs = [ pkgs.imagemagick ];
            # The VM test itself, for its log.
            passthru = { inherit test; };
          }
          ''
            mkdir $out
            if [ -f ${test}/screen.png ]; then
              magick ${test}/screen.png -resize '1280x800!' -quality 85 $out/${d.id}.jpg
            else
              echo "warning: ${d.id}: its session didn't come up, see the log of .#desktop-screenshots.perDesktop.${d.id}.test" >&2
            fi
          ''
      )
    ) desktops
  );

  # Pictures of desktops no VM here can boot (data/screenshots).
  static = lib.fileset.toSource {
    root = ../../data/screenshots;
    fileset = lib.fileset.fileFilter (f: f.hasExt "jpg") ../../data/screenshots;
  };
in
pkgs.symlinkJoin {
  name = "desktop-screenshots";
  paths = builtins.attrValues (removeAttrs perDesktop broken) ++ [ static ];
  passthru = { inherit perDesktop; };
}
