# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch
# (/etc/nixos is this folder, /home/sam/.config/nixos.)
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: Cinnamon.
  services.xserver.desktopManager.cinnamon.enable = true;
  services.xserver.enable = true;

  # Login manager.
  services.xserver.displayManager.lightdm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [ pkgs.firefox ];
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  programs.dconf.enable = true;
  programs.dconf.profiles.user.databases = [
    {
      settings = {
        "org/cinnamon/desktop/keybindings" = {
          custom-list = [ "configurator0" "configurator1" ];
        };
        "org/cinnamon/desktop/keybindings/custom-keybindings/configurator0" = {
          name = "Run firefox --private-window";
          command = "firefox --private-window";
          binding = [ "<Control><Alt>b" ];
        };
        "org/cinnamon/desktop/keybindings/custom-keybindings/configurator1" = {
          name = "Launch alacritty";
          command = lib.getExe pkgs.alacritty;
          binding = [ "<Super>Return" ];
        };
      };
    }
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.sam = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "cinnamon";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/sam/.config/nixos" ];
  environment.etc.nixos.source = "/home/sam/.config/nixos";
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
