//! Turns answers into the user's host flake: `flake.nix` (the pinned
//! inputs and the machine), `configuration.nix` (the choices, one section
//! per layer), `hardware.nix`, `disko.nix` and the desktop's state files.
//!
//! The output is the product: plain, readable Nix the user owns. Desktop
//! modules are imported from their flakes, never copied in.

mod keybinds;
pub mod nix;

use std::collections::BTreeMap;

use configurator_answers::{
    Answers, Filesystem, Firmware, LoginManager, NvidiaDriver, ShellKind, User,
};
use configurator_catalog::{Catalog, Desktop, Session, ShellOption};
use serde_json::Value;

use nix::{Key, Nix};

/// The NixOS release the generated flakes follow.
pub const NIXOS_RELEASE: &str = "26.05";

/// Where disko reads the LUKS passphrase from while formatting. The engine
/// writes it there (on the live system's tmpfs) and removes it after.
pub const LUKS_KEY_FILE: &str = "/tmp/configurator-luks.key";

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("unknown desktop {0:?}")]
    UnknownDesktop(String),
    #[error("the catalog entry {0:?} is invalid: {1}")]
    BadCatalog(String, String),
    #[error("not supported yet: {0}")]
    Unsupported(String),
    #[error("unknown {0} {1:?}")]
    Unknown(&'static str, String),
    #[error("keybinds: {0}")]
    Keybind(String),
}

/// The generated host flake: file paths relative to its root, and contents.
#[derive(Debug, Default, Clone, PartialEq)]
pub struct Host {
    pub files: BTreeMap<String, String>,
}

/// What the generator needs besides the answers.
#[derive(Debug, Default, Clone)]
pub struct Inputs<'a> {
    /// The nixos-facter report (`facter.json`), when hardware was detected.
    pub facter_report: Option<&'a str>,
    /// The Nix system to build for; `None` for `x86_64-linux`.
    pub platform: Option<&'a str>,
}

/// The Nix system of the machine this runs on, e.g. `x86_64-linux`.
pub fn current_platform() -> String {
    format!("{}-linux", std::env::consts::ARCH)
}

/// Where the host flake lives on the installed system: the first admin's
/// `~/.config/nixos`, so the user owns it and desktop menus can edit and
/// rebuild it.
pub fn config_dir(answers: &Answers) -> String {
    let admin = answers
        .users
        .iter()
        .find(|u| u.admin)
        .unwrap_or(&answers.users[0]);
    format!("/home/{}/.config/nixos", admin.name)
}

pub fn generate(answers: &Answers, catalog: &Catalog, inputs: &Inputs) -> Result<Host, Error> {
    let desktop = match &answers.desktop {
        Some(d) => Some(
            catalog
                .desktop(&d.id)
                .ok_or_else(|| Error::UnknownDesktop(d.id.clone()))?,
        ),
        None => None,
    };
    if let Some(d) = desktop
        && let Some(why) = &d.unavailable
    {
        return Err(Error::Unsupported(format!(
            "{} can't be installed with this nixpkgs: {why}",
            d.name
        )));
    }
    let generator = Generator {
        answers,
        catalog,
        desktop,
        config_dir: config_dir(answers),
    };

    let mut host = Host::default();
    host.files.insert("flake.nix".into(), generator.flake());
    host.files
        .insert("configuration.nix".into(), generator.configuration()?);
    host.files.insert(
        "hardware.nix".into(),
        generator.hardware(
            inputs.facter_report.is_some(),
            inputs.platform.unwrap_or("x86_64-linux"),
        )?,
    );
    host.files.insert("disko.nix".into(), generator.disko());
    if let Some(report) = inputs.facter_report {
        host.files.insert("facter.json".into(), report.to_owned());
    }
    if let Some(desktop) = desktop {
        for (path, content) in &desktop.module.files {
            let mut content = content.clone();
            if let Some(state) = &desktop.module.containers
                && state.file == *path
            {
                content[&state.key] = generator
                    .desktop_containers()
                    .into_iter()
                    .cloned()
                    .collect();
            }
            let json = serde_json::to_string_pretty(&content).expect("JSON value serializes");
            host.files.insert(path.clone(), json + "\n");
        }
    }
    Ok(host)
}

struct Generator<'a> {
    answers: &'a Answers,
    catalog: &'a Catalog,
    desktop: Option<&'a Desktop>,
    config_dir: String,
}

/// A commented group of option assignments in a module.
struct Section {
    comment: String,
    entries: Vec<(Key, Nix)>,
}

impl Section {
    fn new(comment: impl Into<String>) -> Section {
        Section {
            comment: comment.into(),
            entries: Vec::new(),
        }
    }

    fn set(&mut self, key: impl Into<Key>, value: Nix) -> &mut Section {
        self.entries.push((key.into(), value));
        self
    }
}

const HEADER: &str = "# Generated by the Configurator (github:nix-composer/configurator).\n\
                      # This is your system now: edit it freely.\n";

fn module(header: &str, args: &str, sections: &[Section]) -> String {
    let mut out = format!("{HEADER}{header}{args}:\n{{\n");
    // Nix rejects an attribute defined twice in one set; the first section
    // that sets an option (e.g. services.xserver.enable) keeps it.
    let mut seen = std::collections::BTreeSet::new();
    let mut first = true;
    for section in sections {
        let entries: Vec<_> = section
            .entries
            .iter()
            .filter(|(key, _)| seen.insert(key.render()))
            .collect();
        if entries.is_empty() {
            continue;
        }
        if !first {
            out.push('\n');
        }
        first = false;
        for line in section.comment.lines() {
            out.push_str(&format!("  # {line}\n"));
        }
        for (key, value) in entries {
            out.push_str(&format!("  {} = {};\n", key.render(), value.render(1)));
        }
    }
    out.push_str("}\n");
    out
}

fn follows_nixpkgs(url: &str) -> Nix {
    Nix::attrs([
        ("url", Nix::str(url)),
        ("inputs.nixpkgs.follows", Nix::str("nixpkgs")),
    ])
}

impl Generator<'_> {
    fn flake_module(&self) -> Option<&configurator_catalog::FlakeModule> {
        self.desktop.and_then(|d| d.module.flake.as_ref())
    }

    fn needs_home_manager(&self) -> bool {
        self.flake_module().is_some_and(|f| f.home_manager)
    }

    fn flake(&self) -> String {
        let a = self.answers;
        let mut inputs = vec![
            (
                Key::from("nixpkgs.url"),
                Nix::str(format!("github:NixOS/nixpkgs/nixos-{NIXOS_RELEASE}")),
            ),
            (
                Key::from("disko"),
                follows_nixpkgs("github:nix-community/disko"),
            ),
        ];
        let mut modules = vec![Nix::raw("inputs.disko.nixosModules.disko")];

        if self.needs_home_manager() {
            inputs.push((
                Key::from("home-manager"),
                follows_nixpkgs(&format!(
                    "github:nix-community/home-manager/release-{NIXOS_RELEASE}"
                )),
            ));
            modules.push(Nix::raw("inputs.home-manager.nixosModules.home-manager"));
        }
        if let Some(flake) = self.flake_module() {
            let mut input = vec![(Key::from("url"), Nix::str(&flake.url))];
            for follow in &flake.follows {
                input.push((
                    Key(vec!["inputs".into(), follow.clone(), "follows".into()]),
                    Nix::str(follow),
                ));
            }
            inputs.push((Key(vec![flake.input.clone()]), Nix::Attrs(input)));
            modules.push(Nix::raw(format!(
                "inputs.{}.{}",
                flake.input, flake.nixos_module
            )));
        }
        if a.security.secure_boot {
            inputs.push((
                Key::from("lanzaboote"),
                follows_nixpkgs("github:nix-community/lanzaboote"),
            ));
            modules.push(Nix::raw("inputs.lanzaboote.nixosModules.lanzaboote"));
        }
        if a.security.tpm_pin {
            // First-boot tasks (TPM2 + PIN sealing) from the configurator.
            inputs.push((
                Key::from("configurator"),
                follows_nixpkgs("github:nix-composer/configurator"),
            ));
            modules.push(Nix::raw("inputs.configurator.nixosModules.default"));
        }
        modules.extend(["./disko.nix", "./hardware.nix", "./configuration.nix"].map(Nix::raw));

        let system = Nix::attrs([
            ("specialArgs", Nix::raw("{ inherit inputs; }")),
            ("modules", Nix::List(modules)),
        ]);
        let outputs = Nix::attrs([(
            Key(vec!["nixosConfigurations".into(), a.hostname.clone()]),
            Nix::raw(format!("nixpkgs.lib.nixosSystem {}", system.render(2))),
        )]);
        let flake = Nix::attrs([
            (
                Key::from("description"),
                Nix::str(format!("NixOS configuration of {}", a.hostname)),
            ),
            (Key::from("inputs"), Nix::Attrs(inputs)),
            (
                Key::from("outputs"),
                Nix::Lambda("{ nixpkgs, ... }@inputs".into(), Box::new(outputs)),
            ),
        ]);
        format!(
            "{HEADER}# Apply changes with: sudo nixos-rebuild switch --flake {}\n{}\n",
            self.config_dir,
            flake.render(0)
        )
    }

    fn configuration(&self) -> Result<String, Error> {
        let a = self.answers;
        let mut sections = Vec::new();

        let mut basics = Section::new(format!(
            "Basics: language, keyboard and time zone. The time zone ({}) was set\n\
             during the install and is yours to change (your desktop's settings or\n\
             `timedatectl set-timezone`); set time.timeZone to fix it here instead.",
            a.basics.timezone
        ));
        basics
            .set("i18n.defaultLocale", Nix::str(&a.basics.locale))
            .set(
                "services.xserver.xkb.layout",
                Nix::str(&a.basics.keyboard_layout),
            );
        if !a.basics.keyboard_variant.is_empty() {
            basics.set(
                "services.xserver.xkb.variant",
                Nix::str(&a.basics.keyboard_variant),
            );
        }
        basics
            .set("console.useXkbConfig", Nix::Bool(true))
            .set("time.timeZone", Nix::raw("null"));
        sections.push(basics);

        sections.push(self.profile_section()?);
        sections.push(self.desktop_section()?);
        sections.push(self.login_manager_section());
        sections.push(self.apps_section()?);
        sections.push(self.development_section()?);
        sections.push(self.shell_section());
        sections.push(self.keybinds_section()?);
        sections.push(self.boot_and_security_section());
        sections.push(self.users_section());

        let mut system = Section::new("System.");
        system
            .set("networking.hostName", Nix::str(&a.hostname))
            .set("networking.networkmanager.enable", Nix::Bool(true))
            // This flake is a git repository the user owns; root rebuilds it.
            .set("programs.git.enable", Nix::Bool(true))
            .set(
                "programs.git.config.safe.directory",
                Nix::List(vec![Nix::str(&self.config_dir)]),
            )
            .set(
                "nix.settings.experimental-features",
                Nix::List(vec![Nix::str("nix-command"), Nix::str("flakes")]),
            )
            .set("system.stateVersion", Nix::str(NIXOS_RELEASE));
        sections.push(system);

        let header = format!(
            "# Your choices, one section per installer layer. Apply changes with:\n\
             #   sudo nixos-rebuild switch --flake {}\n",
            self.config_dir
        );
        // Web app launchers take their icons from the configurator input.
        let rendered = module(&header, "{ lib, pkgs, ... }", &sections);
        Ok(if rendered.contains("${inputs.") {
            module(&header, "{ inputs, lib, pkgs, ... }", &sections)
        } else {
            rendered
        })
    }

    fn desktop_section(&self) -> Result<Section, Error> {
        let Some(desktop) = self.desktop else {
            return Ok(Section::new("Desktop: none."));
        };
        let mut section = Section::new(format!("Desktop: {}.", desktop.name));
        for (path, value) in &desktop.module.config {
            section.set(path.as_str(), self.resolve(&desktop.id, value)?);
        }
        // The ecosystem's apps are in the answers' app and shell lists (as
        // preselected and kept); a desktop with its own switch gets it too.
        if self.answers.desktop.as_ref().is_some_and(|d| d.ecosystem)
            && let Some(option) = &desktop.module.ecosystem
        {
            section.set(option.as_str(), Nix::Bool(true));
        }
        // Its own packages come prebuilt from its binary cache.
        if let Some(cache) = self.flake_module().and_then(|f| f.cache.as_ref()) {
            section
                .set(
                    "nix.settings.extra-substituters",
                    Nix::List(vec![Nix::str(&cache.url)]),
                )
                .set(
                    "nix.settings.extra-trusted-public-keys",
                    Nix::List(vec![Nix::str(&cache.public_key)]),
                )
                // Built here when the cache can't give it (not there yet,
                // a failed download) or doesn't answer quickly.
                .set("nix.settings.fallback", Nix::Bool(true))
                .set("nix.settings.connect-timeout", Nix::Int(10));
        }
        Ok(section)
    }

    /// The registry's JSON, with its special objects resolved.
    /// Catalog JSON (desktop modules, profiles) with its special values
    /// resolved; `owner` names the entry in errors.
    fn resolve(&self, owner: &str, value: &Value) -> Result<Nix, Error> {
        let bad = |msg: String| Error::BadCatalog(owner.to_owned(), msg);
        if let Value::Object(map) = value {
            if let Some(path) = map.get("$path") {
                let path = path
                    .as_str()
                    .filter(|p| p.starts_with("./"))
                    .ok_or_else(|| bad("$path must be \"./…\"".into()))?;
                return Ok(Nix::Path(path.to_owned()));
            }
            if let Some(name) = map.get("$context") {
                return match name.as_str() {
                    Some("users") => Ok(Nix::List(
                        self.answers
                            .users
                            .iter()
                            .map(|u| Nix::str(&u.name))
                            .collect(),
                    )),
                    Some("firstUser") => Ok(Nix::str(&self.answers.users[0].name)),
                    Some("configDir") => Ok(Nix::str(&self.config_dir)),
                    other => Err(bad(format!("unknown $context {other:?}"))),
                };
            }
            // Nix code from the catalog (reviewed data, never user input).
            if let Some(code) = map.get("$expr") {
                let code = code
                    .as_str()
                    .ok_or_else(|| bad("$expr must be a string".into()))?;
                return Ok(Nix::raw(format!("({code})")));
            }
            return Ok(Nix::Attrs(
                map.iter()
                    .map(|(k, v)| Ok((Nix::attr(k), self.resolve(owner, v)?)))
                    .collect::<Result<_, Error>>()?,
            ));
        }
        if let Value::Array(items) = value {
            return Ok(Nix::List(
                items
                    .iter()
                    .map(|v| self.resolve(owner, v))
                    .collect::<Result<_, _>>()?,
            ));
        }
        Ok(Nix::from(value))
    }

    fn login_manager(&self) -> Option<LoginManager> {
        if self.answers.login_manager.is_some() {
            return self.answers.login_manager;
        }
        let default = &self.desktop?.login_manager;
        // "builtin": the desktop's module sets up its own.
        serde_json::from_value(Value::String(default.clone())).ok()
    }

    fn login_manager_section(&self) -> Section {
        let mut section = Section::new("Login manager.");
        let wayland_only = self
            .desktop
            .is_some_and(|d| !d.sessions.contains(&Session::X11));
        match self.login_manager() {
            Some(LoginManager::Gdm) => {
                section.set("services.displayManager.gdm.enable", Nix::Bool(true));
            }
            Some(LoginManager::Sddm) => {
                section.set("services.displayManager.sddm.enable", Nix::Bool(true));
                if wayland_only {
                    section.set(
                        "services.displayManager.sddm.wayland.enable",
                        Nix::Bool(true),
                    );
                }
            }
            Some(LoginManager::Lightdm) => {
                section.set("services.xserver.enable", Nix::Bool(true)).set(
                    "services.xserver.displayManager.lightdm.enable",
                    Nix::Bool(true),
                );
            }
            Some(LoginManager::CosmicGreeter) => {
                section.set(
                    "services.displayManager.cosmic-greeter.enable",
                    Nix::Bool(true),
                );
            }
            Some(LoginManager::Ly) => {
                section.set("services.displayManager.ly.enable", Nix::Bool(true));
            }
            Some(LoginManager::None) | None => {}
        }
        section
    }

    fn apps_section(&self) -> Result<Section, Error> {
        let a = self.answers;
        let module = self.desktop.map(|d| &d.module);

        // Agents the desktop takes through its own option (Omarchy's agents
        // panel) go there; the rest are installed as packages.
        let agents_option = module.and_then(|m| m.agents.as_ref());
        let mut desktop_agents = Vec::new();
        let mut agent_packages = Vec::new();
        for id in &a.apps.agents {
            let agent = self
                .catalog
                .agent(id)
                .ok_or_else(|| Error::Unknown("agent", id.clone()))?;
            if agents_option.is_some_and(|o| o.ids.contains(id)) {
                desktop_agents.push(Nix::str(id));
            } else {
                agent_packages.push(&agent.attr);
            }
        }
        if let Some(id) = &a.apps.default_agent
            && !agents_option.is_some_and(|o| o.ids.contains(id))
        {
            return Err(Error::Unsupported(format!(
                "a default agent ({id}) on a desktop without an agents option for it"
            )));
        }

        // Likewise web apps: the desktop's own launchers where it has them,
        // generic app-window launchers otherwise.
        let webapps_option = module.and_then(|m| m.webapps.as_ref());
        let mut desktop_webapps = Vec::new();
        let mut launchers = Vec::new();
        for id in &a.webapps {
            let webapp = self
                .catalog
                .webapp(id)
                .ok_or_else(|| Error::Unknown("web app", id.clone()))?;
            if webapps_option.is_some_and(|o| o.ids.contains(id)) {
                desktop_webapps.push(Nix::str(id));
            } else {
                let mut item = vec![
                    ("name", Nix::str(format!("webapp-{}", webapp.id))),
                    ("desktopName", Nix::str(&webapp.name)),
                    ("comment", Nix::str(&webapp.description)),
                    ("exec", self.webapp_command(id)?),
                    ("categories", Nix::List(vec![Nix::str("Network")])),
                ];
                // Its icon from the web app store (the configurator input).
                if self.catalog.webapp_icon(id).is_some() {
                    item.push((
                        "icon",
                        Nix::raw(nix::string_interpolated(
                            "inputs.configurator",
                            &format!("/data/webapps/{id}.png"),
                        )),
                    ));
                }
                launchers.push(Nix::raw(format!(
                    "(pkgs.makeDesktopItem {})",
                    Nix::attrs(item).render(2)
                )));
            }
        }

        // A flake desktop's own apps and tools (Omarchy's) go through its
        // options: the apps kept as picks, the tools dropped as opt-outs.
        // What it installs itself (with its configs and keybinds) isn't
        // listed again; what it would install only on first use is.
        let ecosystem = a.desktop.as_ref().is_some_and(|d| d.ecosystem);
        let own = self.desktop.and_then(|d| self.catalog.desktop_catalog(d));
        let mut installed_by_desktop = std::collections::BTreeSet::new();
        let mut app_picks = Vec::new();
        let mut cli_off = Vec::new();
        if let Some((options, cat)) = own {
            for (id, entry) in cat.group("apps").filter(|(_, e)| e.packaged) {
                match cat.store_attr(&options.name, entry) {
                    Some(attr) if a.apps.packages.iter().any(|p| p == attr) => {
                        app_picks.push(Nix::str(id));
                        if entry.preinstalled {
                            installed_by_desktop.insert(attr);
                        }
                    }
                    Some(_) => {}
                    // Its own tools aren't in the app store: they come
                    // with the ecosystem.
                    None if ecosystem => app_picks.push(Nix::str(id)),
                    None => {}
                }
            }
            for (id, entry) in cat.group("cli") {
                if let Some(attr) = cat.store_attr(&options.name, entry) {
                    installed_by_desktop.insert(attr);
                    if a.shell.without.iter().any(|p| p == attr) {
                        cli_off.push(id);
                    }
                }
            }
        }

        // The desktop's essentials come with its module; the ones taken
        // out in the app store go to its exclude option.
        let essentials = self.desktop.and_then(|d| self.catalog.ecosystem(&d.id));
        let mut excluded = Vec::new();
        if let Some(eco) = essentials {
            installed_by_desktop.extend(eco.essentials.iter().map(String::as_str));
            let removable = eco.removable();
            for attr in &a.apps.without {
                if removable.contains(&attr.as_str()) {
                    excluded.push(Nix::raw(format!("pkgs.{attr}")));
                }
            }
        }

        // Apps NixOS sets up through their own module (Steam, Wireshark, …)
        // get that module instead of a bare package.
        let programs: Vec<_> = a
            .all_packages()
            .chain(agent_packages.iter().copied())
            .filter(|attr| !installed_by_desktop.contains(attr.as_str()))
            .filter_map(|attr| self.catalog.program(attr))
            .collect();

        let mut section = Section::new("Apps, web apps, AI agents and command-line tools.");
        let mut seen = std::collections::BTreeSet::new();
        let mut packages: Vec<Nix> = a
            .all_packages()
            .chain(agent_packages)
            .filter(|attr| !installed_by_desktop.contains(attr.as_str()))
            .filter(|attr| {
                self.catalog
                    .program(attr)
                    .is_none_or(|program| program.package)
            })
            .filter(|attr| seen.insert(attr.as_str()))
            .map(|attr| Nix::raw(format!("pkgs.{attr}")))
            .collect();
        packages.extend(launchers);
        if !packages.is_empty() {
            section.set("environment.systemPackages", Nix::List(packages));
        }
        if let Some(option) = essentials.and_then(|e| e.exclude.as_ref())
            && !excluded.is_empty()
        {
            section.set(option.as_str(), Nix::List(excluded));
        }
        let mut configured = std::collections::BTreeSet::new();
        for program in programs {
            if configured.insert(&program.attr) {
                for (path, value) in &program.config {
                    section.set(path.as_str(), self.resolve(&program.attr, value)?);
                }
            }
        }
        // The app store marks unfree apps; accepting them is part of picking one.
        section.set("nixpkgs.config.allowUnfree", Nix::Bool(true));

        if let Some(option) = agents_option
            && !desktop_agents.is_empty()
        {
            self.desktop_option(
                &mut section,
                &option.option,
                option.home,
                Nix::List(desktop_agents),
            );
            if let Some(id) = &a.apps.default_agent {
                self.desktop_option(
                    &mut section,
                    &option.default_option,
                    option.home,
                    Nix::str(id),
                );
            }
        }
        if let Some((options, _)) = own {
            if ecosystem || !app_picks.is_empty() {
                // With the ecosystem on, the picks narrow its apps down to
                // the ones kept in the app store.
                let value = Nix::attrs([
                    ("enable", Nix::Bool(!app_picks.is_empty())),
                    ("picks", Nix::List(app_picks)),
                ]);
                self.desktop_option(&mut section, &options.apps, options.home, value);
            }
            // Its command-line setup, less the tools dropped in the shell layer.
            for id in cli_off {
                self.desktop_option(
                    &mut section,
                    &format!("{}.{id}.enable", options.cli),
                    options.home,
                    Nix::Bool(false),
                );
            }
        }
        if let Some(option) = webapps_option
            && (ecosystem || !desktop_webapps.is_empty())
        {
            // With the ecosystem on, the picks narrow its web apps down to
            // the ones kept in the web app store.
            let value = Nix::attrs([
                ("enable", Nix::Bool(!desktop_webapps.is_empty())),
                ("picks", Nix::List(desktop_webapps)),
            ]);
            self.desktop_option(&mut section, &option.option, option.home, value);
        }
        Ok(section)
    }

    /// Sets a desktop module option, per user when it's a Home Manager one.
    fn desktop_option(&self, section: &mut Section, option: &str, home: bool, value: Nix) {
        if home {
            for user in &self.answers.users {
                let mut key = vec!["home-manager".into(), "users".into(), user.name.clone()];
                key.extend(Key::from(option).0);
                section.set(Key(key), value.clone());
            }
        } else {
            section.set(option, value);
        }
    }

    /// Opens a web app in its own window, as a Nix string expression.
    fn webapp_command(&self, id: &str) -> Result<Nix, Error> {
        let webapp = self
            .catalog
            .webapp(id)
            .ok_or_else(|| Error::Unknown("web app", id.to_owned()))?;
        Ok(Nix::raw(format!(
            "(lib.getExe pkgs.chromium + {})",
            nix::string(&format!(" --app={}", webapp.url))
        )))
    }

    fn profile_section(&self) -> Result<Section, Error> {
        let id = &self.answers.profile;
        let profile = self
            .catalog
            .profile(id)
            .ok_or_else(|| Error::Unknown("profile", id.clone()))?;
        let mut section = Section::new(format!("Profile: {}.", profile.name));
        for (path, value) in &profile.config {
            section.set(path.as_str(), self.resolve(&profile.id, value)?);
        }
        Ok(section)
    }

    /// Container picks the desktop keeps in its own state (Omarchy's
    /// dbs.json).
    fn desktop_containers(&self) -> Vec<&String> {
        let ids = self
            .desktop
            .and_then(|d| d.module.containers.as_ref())
            .map(|c| &c.ids);
        let containers = &self.answers.development.containers;
        containers
            .iter()
            .filter(|id| ids.is_some_and(|ids| ids.contains(id)))
            .collect()
    }

    /// Containers that become oci-containers units here.
    fn own_containers(&self) -> Vec<&String> {
        let desktop = self.desktop_containers();
        self.answers
            .development
            .containers
            .iter()
            .filter(|id| !desktop.contains(id))
            .collect()
    }

    fn development_section(&self) -> Result<Section, Error> {
        let dev = &self.answers.development;
        let mut comment = String::from("Development.");
        let mut section = Section::new("");
        if !dev.templates.is_empty() {
            // Dev environments are per project: direnv loads them, and the
            // `dev` registry entry names the templates.
            comment.push_str(" Start a project from a template with:");
            for id in &dev.templates {
                self.catalog
                    .dev_template(id)
                    .ok_or_else(|| Error::Unknown("dev template", id.clone()))?;
                comment.push_str(&format!(
                    "\n  nix flake new -t dev#{id} ~/Projects/my-{id}-project"
                ));
            }
            section.set("programs.direnv.enable", Nix::Bool(true)).set(
                "nix.registry.dev.to",
                Nix::attrs([
                    ("type", Nix::str("github")),
                    ("owner", Nix::str("nix-templates")),
                    ("repo", Nix::str("dev")),
                ]),
            );
        }
        let own = self.own_containers();
        if !own.is_empty() {
            section
                .set("virtualisation.docker.enable", Nix::Bool(true))
                .set("virtualisation.oci-containers.backend", Nix::str("docker"));
            for id in own {
                let c = self
                    .catalog
                    .container(id)
                    .ok_or_else(|| Error::Unknown("container", id.clone()))?;
                let mut unit = vec![
                    (Key::from("image"), Nix::str(&c.image)),
                    (
                        Key::from("ports"),
                        Nix::List(c.ports.iter().map(Nix::str).collect()),
                    ),
                ];
                if !c.environment.is_empty() {
                    unit.push((
                        Key::from("environment"),
                        Nix::Attrs(
                            c.environment
                                .iter()
                                .map(|(k, v)| (Nix::attr(k), Nix::str(v)))
                                .collect(),
                        ),
                    ));
                }
                unit.push((
                    Key::from("volumes"),
                    Nix::List(c.volumes.iter().map(Nix::str).collect()),
                ));
                if !c.cmd.is_empty() {
                    unit.push((
                        Key::from("cmd"),
                        Nix::List(c.cmd.iter().map(Nix::str).collect()),
                    ));
                }
                if let Some(user) = &c.user {
                    unit.push((Key::from("user"), Nix::str(user)));
                }
                if !c.extra_options.is_empty() {
                    unit.push((
                        Key::from("extraOptions"),
                        Nix::List(c.extra_options.iter().map(Nix::str).collect()),
                    ));
                }
                section.set(
                    Key(vec![
                        "virtualisation".into(),
                        "oci-containers".into(),
                        "containers".into(),
                        c.id.clone(),
                    ]),
                    Nix::Attrs(unit),
                );
            }
        }
        for id in self.desktop_containers() {
            self.catalog
                .container(id)
                .ok_or_else(|| Error::Unknown("container", id.clone()))?;
        }
        section.comment = comment;
        Ok(section)
    }

    /// The chosen shell's name and package.
    fn shell(&self) -> (&'static str, &'static str) {
        match self.answers.shell.shell {
            ShellKind::Bash => ("bash", "pkgs.bashInteractive"),
            ShellKind::Zsh => ("zsh", "pkgs.zsh"),
            ShellKind::Fish => ("fish", "pkgs.fish"),
            ShellKind::Nushell => ("nushell", "pkgs.nushell"),
        }
    }

    /// A desktop that sets users' shells itself (Omarchy): whether it has a
    /// setup for the chosen shell (then it gets told which), else users get
    /// the shell set directly, over the desktop's.
    fn desktop_shell(&self) -> Option<(&ShellOption, bool)> {
        let option = self.desktop?.module.shell.as_ref()?;
        let (name, _) = self.shell();
        Some((option, option.values.iter().any(|v| v == name)))
    }

    fn shell_section(&self) -> Section {
        let mut section = Section::new("Shell.");
        if let Some((option, true)) = self.desktop_shell() {
            section.set(option.option.as_str(), Nix::str(self.shell().0));
        }
        match self.answers.shell.shell {
            ShellKind::Bash => {}
            ShellKind::Zsh => {
                section
                    .set("programs.zsh.enable", Nix::Bool(true))
                    .set("users.defaultUserShell", Nix::raw("pkgs.zsh"));
            }
            ShellKind::Fish => {
                section
                    .set("programs.fish.enable", Nix::Bool(true))
                    .set("users.defaultUserShell", Nix::raw("pkgs.fish"));
            }
            ShellKind::Nushell => {
                section
                    .set(
                        "environment.shells",
                        Nix::List(vec![Nix::raw("pkgs.nushell")]),
                    )
                    .set("users.defaultUserShell", Nix::raw("pkgs.nushell"));
            }
        }
        section
    }

    fn boot_and_security_section(&self) -> Section {
        let s = &self.answers.security;
        let mut section = Section::new("Boot and security.");
        if self.answers.hardware.firmware == Firmware::Bios {
            // Legacy BIOS: GRUB on the disk's BIOS boot partition (disko
            // points boot.loader.grub.devices at it), /boot unencrypted.
            // The kernel keeps GRUB's framebuffer: coreboot (Libreboot's
            // GRUB payload) has no VGA text mode to go back to, so with
            // NixOS's default ("text") the screen stays on GRUB's last
            // picture until a graphics driver loads, past the LUKS prompt.
            section
                .set("boot.loader.grub.enable", Nix::Bool(true))
                .set("boot.loader.grub.gfxpayloadBios", Nix::str("keep"));
        } else if s.secure_boot {
            // lanzaboote replaces systemd-boot and signs the boot files with
            // the keys the installer created and enrolled. Turn Secure Boot
            // on in the firmware after the install.
            section
                .set(
                    "boot.loader.systemd-boot.enable",
                    Nix::raw("lib.mkForce false"),
                )
                .set("boot.lanzaboote.enable", Nix::Bool(true))
                .set("boot.lanzaboote.pkiBundle", Nix::str("/var/lib/sbctl"));
        } else {
            section.set("boot.loader.systemd-boot.enable", Nix::Bool(true));
        }
        if self.answers.hardware.firmware == Firmware::Uefi {
            section.set("boot.loader.efi.canTouchEfiVariables", Nix::Bool(true));
        }
        if s.tpm_pin {
            // Sealed to the TPM2 (PCR 7) with a PIN on the first boot with
            // Secure Boot on; see github:nix-composer/configurator.
            section.set("configurator.tpmPin.enable", Nix::Bool(true));
        }
        if s.fido2 {
            section.set("security.pam.u2f.enable", Nix::Bool(true));
        }
        if s.fingerprint {
            section.set("services.fprintd.enable", Nix::Bool(true));
        }
        section
    }

    fn users_section(&self) -> Section {
        let mut section = Section::new("Users. Passwords are set during install, not stored here.");
        let docker = !self.own_containers().is_empty();
        // With keys to log in with, SSH needs no passwords.
        if self.answers.users.iter().any(|u| !u.ssh_keys.is_empty()) {
            section.set("services.openssh.enable", Nix::Bool(true)).set(
                "services.openssh.settings.PasswordAuthentication",
                Nix::Bool(false),
            );
        }
        for user in &self.answers.users {
            section.set(
                Key(vec!["users".into(), "users".into(), user.name.clone()]),
                user_config(
                    user,
                    docker,
                    // Over a desktop that sets shells and has no setup for this one.
                    matches!(self.desktop_shell(), Some((_, false))).then(|| self.shell().1),
                ),
            );
        }
        if self.needs_home_manager() {
            section
                .set("home-manager.useGlobalPkgs", Nix::Bool(true))
                .set("home-manager.useUserPackages", Nix::Bool(true));
            for user in &self.answers.users {
                section.set(
                    Key(vec![
                        "home-manager".into(),
                        "users".into(),
                        user.name.clone(),
                        "home".into(),
                        "stateVersion".into(),
                    ]),
                    Nix::str(NIXOS_RELEASE),
                );
            }
        }
        section
    }

    fn hardware(&self, has_report: bool, platform: &str) -> Result<String, Error> {
        let h = &self.answers.hardware;
        let mut detected =
            Section::new("What nixos-facter detected: kernel modules, firmware, CPU microcode, …");
        // The report sets it too; this keeps the flake evaluating without one.
        detected.set(
            "nixpkgs.hostPlatform",
            Nix::raw(format!("lib.mkDefault {}", nix::string(platform))),
        );
        if has_report {
            detected.set(
                "hardware.facter.reportPath",
                Nix::Path("./facter.json".into()),
            );
        }

        let mut drivers = Section::new("Driver choices.");
        match h.nvidia {
            Some(NvidiaDriver::Open) | Some(NvidiaDriver::Proprietary) => {
                drivers
                    .set(
                        "services.xserver.videoDrivers",
                        Nix::List(vec![Nix::str("nvidia")]),
                    )
                    .set(
                        "hardware.nvidia.open",
                        Nix::Bool(h.nvidia == Some(NvidiaDriver::Open)),
                    )
                    .set("hardware.graphics.enable", Nix::Bool(true));
            }
            // nouveau is the default.
            Some(NvidiaDriver::Nouveau) | None => {}
        }
        let kernel = self
            .catalog
            .kernel(&h.kernel)
            .ok_or_else(|| Error::Unknown("kernel", h.kernel.clone()))?;
        if !kernel.is_default() {
            drivers.set(
                "boot.kernelPackages",
                Nix::raw(format!("pkgs.{}", kernel.attr)),
            );
        }
        if h.non_free_firmware {
            drivers.set("hardware.enableAllFirmware", Nix::Bool(true));
        } else {
            drivers.set("hardware.enableRedistributableFirmware", Nix::Bool(true));
        }

        let header = if has_report {
            ""
        } else {
            "# No hardware report yet. On the machine, run\n\
             #   sudo nixos-facter -o facter.json\n\
             # here and set hardware.facter.reportPath = ./facter.json;\n"
        };
        let args = if !kernel.is_default() {
            "{ lib, pkgs, ... }"
        } else {
            "{ lib, ... }"
        };
        Ok(module(header, args, &[detected, drivers]))
    }

    fn disko(&self) -> String {
        let d = &self.answers.disk;
        let swap = (d.swap_gib > 0).then(|| format!("{}G", d.swap_gib));

        let root_fs = match d.filesystem {
            Filesystem::Btrfs => {
                let opts = || Nix::List(vec![Nix::str("compress=zstd"), Nix::str("noatime")]);
                let mut subvolumes = vec![
                    (
                        Nix::attr("@"),
                        Nix::attrs([("mountpoint", Nix::str("/")), ("mountOptions", opts())]),
                    ),
                    (
                        Nix::attr("@home"),
                        Nix::attrs([("mountpoint", Nix::str("/home")), ("mountOptions", opts())]),
                    ),
                    (
                        Nix::attr("@nix"),
                        Nix::attrs([("mountpoint", Nix::str("/nix")), ("mountOptions", opts())]),
                    ),
                    (
                        Nix::attr("@snapshots"),
                        Nix::attrs([
                            ("mountpoint", Nix::str("/.snapshots")),
                            ("mountOptions", opts()),
                        ]),
                    ),
                ];
                if let Some(size) = &swap {
                    subvolumes.push((
                        Nix::attr("@swap"),
                        Nix::attrs([
                            ("mountpoint", Nix::str("/.swapvol")),
                            ("swap.swapfile.size", Nix::str(size)),
                        ]),
                    ));
                }
                Nix::attrs([
                    ("type", Nix::str("btrfs")),
                    ("extraArgs", Nix::List(vec![Nix::str("-f")])),
                    ("subvolumes", Nix::Attrs(subvolumes)),
                ])
            }
            Filesystem::Ext4 | Filesystem::Xfs => Nix::attrs([
                ("type", Nix::str("filesystem")),
                (
                    "format",
                    Nix::str(if d.filesystem == Filesystem::Ext4 {
                        "ext4"
                    } else {
                        "xfs"
                    }),
                ),
                ("mountpoint", Nix::str("/")),
            ]),
        };
        let root_content = if d.encryption {
            Nix::attrs([
                ("type", Nix::str("luks")),
                ("name", Nix::str("cryptroot")),
                ("passwordFile", Nix::str(LUKS_KEY_FILE)),
                ("settings.allowDiscards", Nix::Bool(true)),
                ("content", root_fs),
            ])
        } else {
            root_fs
        };

        let mut partitions = match self.answers.hardware.firmware {
            Firmware::Uefi => vec![(
                Key::from("ESP"),
                Nix::attrs([
                    ("size", Nix::str("1G")),
                    ("type", Nix::str("EF00")),
                    (
                        "content",
                        Nix::attrs([
                            ("type", Nix::str("filesystem")),
                            ("format", Nix::str("vfat")),
                            ("mountpoint", Nix::str("/boot")),
                            ("mountOptions", Nix::List(vec![Nix::str("umask=0077")])),
                        ]),
                    ),
                ]),
            )],
            // GRUB's core image goes in the BIOS boot partition; /boot
            // stays unencrypted so any GRUB (Libreboot's too) reads it.
            Firmware::Bios => vec![
                (
                    Key::from("bios"),
                    Nix::attrs([("size", Nix::str("1M")), ("type", Nix::str("EF02"))]),
                ),
                (
                    Key::from("boot"),
                    Nix::attrs([
                        ("size", Nix::str("1G")),
                        (
                            "content",
                            Nix::attrs([
                                ("type", Nix::str("filesystem")),
                                ("format", Nix::str("ext4")),
                                ("mountpoint", Nix::str("/boot")),
                            ]),
                        ),
                    ]),
                ),
            ],
        };
        // btrfs keeps swap in a subvolume; the others get a partition,
        // encrypted with a random key on every boot when the disk is.
        if let (Some(size), false) = (&swap, d.filesystem == Filesystem::Btrfs) {
            partitions.push((
                Key::from("swap"),
                Nix::attrs([
                    ("size", Nix::str(size)),
                    (
                        "content",
                        Nix::attrs([
                            ("type", Nix::str("swap")),
                            ("randomEncryption", Nix::Bool(d.encryption)),
                        ]),
                    ),
                ]),
            ));
        }
        partitions.push((
            Key::from("root"),
            Nix::attrs([("size", Nix::str("100%")), ("content", root_content)]),
        ));

        let disk = Nix::attrs([
            ("type", Nix::str("disk")),
            ("device", Nix::str(&d.device)),
            (
                "content",
                Nix::attrs([
                    ("type", Nix::str("gpt")),
                    ("partitions", Nix::Attrs(partitions)),
                ]),
            ),
        ]);
        let mut layout = Section::new(format!(
            "Disk layout (disko): {}{}{}.",
            match d.filesystem {
                Filesystem::Btrfs => "btrfs with subvolumes",
                Filesystem::Ext4 => "ext4",
                Filesystem::Xfs => "XFS",
            },
            if d.encryption { " on LUKS" } else { "" },
            if self.answers.hardware.firmware == Firmware::Bios {
                ", legacy BIOS boot"
            } else {
                ""
            }
        ));
        layout.set("disko.devices.disk.main", disk);
        module("", "{ ... }", &[layout])
    }
}

fn user_config(user: &User, docker: bool, shell: Option<&str>) -> Nix {
    let mut groups = vec![Nix::str("networkmanager"), Nix::str("video")];
    if docker {
        groups.push(Nix::str("docker"));
    }
    if user.admin {
        groups.insert(0, Nix::str("wheel"));
    }
    let mut entries = vec![(Key::from("isNormalUser"), Nix::Bool(true))];
    if !user.full_name.is_empty() {
        entries.push((Key::from("description"), Nix::str(&user.full_name)));
    }
    entries.push((Key::from("extraGroups"), Nix::List(groups)));
    if !user.ssh_keys.is_empty() {
        entries.push((
            Key::from("openssh.authorizedKeys.keys"),
            Nix::List(user.ssh_keys.iter().map(Nix::str).collect()),
        ));
    }
    if let Some(shell) = shell {
        entries.push((Key::from("shell"), Nix::raw(shell)));
    }
    Nix::Attrs(entries)
}

#[cfg(test)]
mod tests {
    use super::*;
    use configurator_answers::{Combo, Keybind};
    use std::path::Path;

    /// Generated output for each answers file in `examples/answers` and
    /// `nix/tests/answers` is checked in next to it, under `hosts/<name>/`
    /// (the VM tests install those). Set `UPDATE_EXPECT=1` to regenerate.
    #[test]
    fn omarchy_gets_the_chosen_shell() {
        let catalog = Catalog::builtin().unwrap();
        let mut answers =
            Answers::from_json(include_str!("../../../examples/answers/omarchy.json")).unwrap();
        answers.shell.shell = ShellKind::Bash;
        let host = generate(&answers, &catalog, &Default::default()).unwrap();
        let config = &host.files["configuration.nix"];
        assert!(config.contains(r#"omarchy.shell = "bash";"#), "{config}");
        // A shell Omarchy has no setup for is set per user, over Omarchy's.
        answers.shell.shell = ShellKind::Fish;
        let host = generate(&answers, &catalog, &Default::default()).unwrap();
        let config = &host.files["configuration.nix"];
        assert!(!config.contains("omarchy.shell"), "{config}");
        assert!(config.contains("shell = pkgs.fish;"), "{config}");
    }

    #[test]
    fn examples_match_checked_in_output() {
        let catalog = Catalog::builtin().unwrap();
        let update = std::env::var_os("UPDATE_EXPECT").is_some();
        let mut stale = Vec::new();

        for root in ["../../examples", "../../nix/tests"] {
            let root = Path::new(env!("CARGO_MANIFEST_DIR")).join(root);
            for entry in std::fs::read_dir(root.join("answers")).unwrap() {
                let path = entry.unwrap().path();
                let name = path.file_stem().unwrap().to_str().unwrap().to_owned();
                let answers = Answers::from_json(&std::fs::read_to_string(&path).unwrap()).unwrap();
                let host = generate(&answers, &catalog, &Inputs::default()).unwrap();
                let dir = root.join("hosts").join(&name);
                for (file, content) in &host.files {
                    let target = dir.join(file);
                    if update {
                        std::fs::create_dir_all(target.parent().unwrap()).unwrap();
                        std::fs::write(&target, content).unwrap();
                    } else if std::fs::read_to_string(&target).ok().as_deref() != Some(content) {
                        stale.push(target.display().to_string());
                    }
                }
            }
        }
        assert!(
            stale.is_empty(),
            "stale generated examples (UPDATE_EXPECT=1 cargo test): {stale:?}"
        );
    }

    #[test]
    fn default_keybinds_are_desktops_and_parse() {
        let catalog = Catalog::builtin().unwrap();
        for (id, binds) in &catalog.default_keybinds {
            // A desktop's defaults may come before its renderer: the
            // keybind layer lists them read-only until then.
            assert!(
                catalog.desktop(id).is_some(),
                "data/keybinds/{id}.json: no such desktop"
            );
            for bind in binds {
                for accel in &bind.accels {
                    assert!(
                        Combo::from_gtk_accel(accel).is_some(),
                        "{id}: {}: {accel:?} doesn't parse",
                        bind.action
                    );
                }
            }
        }
    }

    #[test]
    fn omarchy_unbinds_use_its_own_combos() {
        let catalog = Catalog::builtin().unwrap();
        let mut answers =
            Answers::from_json(include_str!("../../../examples/answers/omarchy.json")).unwrap();
        answers.keybinds.clear();
        answers.keybinds.insert("SUPER + 1".into(), Keybind::Unbind);
        let host = generate(&answers, &catalog, &Inputs::default()).unwrap();
        let config = &host.files["configuration.nix"];
        assert!(config.contains("\"SUPER + code:10\""), "{config}");
    }

    #[test]
    fn gnome_actions_move_to_new_keys() {
        let catalog = Catalog::builtin().unwrap();
        let mut answers =
            Answers::from_json(include_str!("../../../examples/answers/gnome.json")).unwrap();
        answers.keybinds.clear();
        // The overview on the right Super key; closing on SUPER + Q, which
        // nothing else holds; and SUPER + S, which the quick settings hold.
        for (combo, action) in [
            ("Super_R", "org.gnome.mutter/overlay-key"),
            ("SUPER + Q", "org.gnome.desktop.wm.keybindings/close"),
        ] {
            answers
                .keybinds
                .insert(combo.into(), Keybind::Action(action.into()));
        }
        answers.keybinds.insert(
            "SUPER + S".into(),
            Keybind::Action("org.gnome.desktop.wm.keybindings/close".into()),
        );
        let host = generate(&answers, &catalog, &Inputs::default()).unwrap();
        let config = &host.files["configuration.nix"];
        assert!(config.contains("overlay-key = \"Super_R\""), "{config}");
        assert!(
            config.contains("close = [ \"<Super>q\" \"<Super>s\" ];"),
            "{config}"
        );
        // SUPER + S left the quick settings (its only key): now empty.
        assert!(
            config.contains("toggle-quick-settings = lib.gvariant.mkEmptyArray"),
            "{config}"
        );
        answers.keybinds.insert(
            "SUPER + Z".into(),
            Keybind::Action("org.gnome.nothing/here".into()),
        );
        assert!(generate(&answers, &catalog, &Inputs::default()).is_err());
    }

    #[test]
    fn containers_carry_cmd_user_and_options() {
        let catalog = Catalog::builtin().unwrap();
        let mut answers =
            Answers::from_json(include_str!("../../../examples/answers/gnome.json")).unwrap();
        answers.development.containers =
            vec!["keycloak".into(), "surrealdb".into(), "grafana".into()];
        let host = generate(&answers, &catalog, &Inputs::default()).unwrap();
        let config = &host.files["configuration.nix"];
        assert!(config.contains("cmd = [ \"start-dev\" ];"), "{config}");
        assert!(config.contains("user = \"root\";"), "{config}");
        assert!(
            config.contains("extraOptions = [ \"--network=host\" ];"),
            "{config}"
        );
        // Every container is known, and generates.
        answers.development.containers = catalog.containers.iter().map(|c| c.id.clone()).collect();
        generate(&answers, &catalog, &Inputs::default()).unwrap();
    }

    #[test]
    fn every_desktop_generates() {
        let catalog = Catalog::builtin().unwrap();
        let base = include_str!("../../../examples/answers/gnome.json");
        for desktop in &catalog.desktops {
            let mut answers = Answers::from_json(base).unwrap();
            answers.desktop.as_mut().unwrap().id = desktop.id.clone();
            answers.desktop.as_mut().unwrap().ecosystem = false;
            // Keybinds are per desktop (tested through the examples).
            answers.keybinds.clear();
            let result = generate(&answers, &catalog, &Inputs::default());
            match &desktop.unavailable {
                None => {
                    result.unwrap_or_else(|e| panic!("{}: {e}", desktop.id));
                }
                // Refused before anything is written.
                Some(_) => assert!(
                    matches!(result, Err(Error::Unsupported(_))),
                    "{}: unavailable but generated",
                    desktop.id
                ),
            }
        }
    }
}
