# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch
# (/etc/nixos is this folder, /home/kim/.config/nixos.)
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: LXQt.
  services.xserver.desktopManager.lxqt.enable = true;
  services.xserver.enable = true;

  # Login manager.
  services.displayManager.sddm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  environment.etc."xdg/openbox/rc.xml".source = pkgs.runCommand "openbox-rc.xml" {
    binds = lib.concatLines [
      "    <keybind key=\"W-F10\"><action name=\"Close\" /></keybind>"
    ];
    passAsFile = [ "binds" ];
    nativeBuildInputs = [ pkgs.perl ];
  } "cp ${pkgs.openbox}/etc/xdg/openbox/rc.xml $out\nchmod +w $out\nperl -0pi -e 's{\\s*<keybind key=\"(?:A-F4)\">.*?</keybind>}{}gs' $out\nsed -i \"/<\\/keyboard>/e cat $bindsPath\" $out\n";
  systemd.user.tmpfiles.rules = [
    "d %h/.config/lxqt 0755 - - -"
    "C %h/.config/lxqt/globalkeyshortcuts.conf - - - - ${pkgs.writeText "globalkeyshortcuts.conf" (lib.concatLines [
    "[General]"
    ""
    "[Alt%2BF1.1]"
    "Comment=Show/hide main menu"
    "Enabled=true"
    "path=/panel/fancymenu/show_hide"
    ""
    "[Alt%2BF2.2]"
    "Comment=Show/hide runner dialog"
    "Enabled=false"
    "path=/runner/show_hide_dialog"
    ""
    "[Control%2BAlt%2BD.3]"
    "Comment=Show desktop"
    "Enabled=true"
    "path=/panel/showdesktop/show_hide"
    ""
    "[Control%2BAlt%2BE.4]"
    "Comment=PCManFM-Qt"
    "Enabled=true"
    "Exec=pcmanfm-qt"
    ""
    "[Control%2BAlt%2BI.5]"
    "Comment=Web Browser"
    "Enabled=true"
    "Exec=xdg-open, about:blank"
    ""
    "[Control%2BAlt%2BL.6]"
    "Comment=Lockscreen"
    "Enabled=true"
    "Exec=xdg-screensaver, lock"
    ""
    "[Control%2BF1.7]"
    "Comment=Switch to desktop 1"
    "Enabled=true"
    "path=/panel/desktopswitch/desktop_1"
    ""
    "[Control%2BF10.8]"
    "Comment=Switch to desktop 10"
    "Enabled=true"
    "path=/panel/desktopswitch/desktop_10"
    ""
    "[Control%2BF11.9]"
    "Comment=Switch to desktop 11"
    "Enabled=true"
    "path=/panel/desktopswitch/desktop_11"
    ""
    "[Control%2BF12.10]"
    "Comment=Switch to desktop 12"
    "Enabled=true"
    "path=/panel/desktopswitch/desktop_12"
    ""
    "[Control%2BF2.11]"
    "Comment=Switch to desktop 2"
    "Enabled=true"
    "path=/panel/desktopswitch/desktop_2"
    ""
    "[Control%2BF3.12]"
    "Comment=Switch to desktop 3"
    "Enabled=true"
    "path=/panel/desktopswitch/desktop_3"
    ""
    "[Control%2BF4.13]"
    "Comment=Switch to desktop 4"
    "Enabled=true"
    "path=/panel/desktopswitch/desktop_4"
    ""
    "[Control%2BF5.14]"
    "Comment=Switch to desktop 5"
    "Enabled=true"
    "path=/panel/desktopswitch/desktop_5"
    ""
    "[Control%2BF6.15]"
    "Comment=Switch to desktop 6"
    "Enabled=true"
    "path=/panel/desktopswitch/desktop_6"
    ""
    "[Control%2BF7.16]"
    "Comment=Switch to desktop 7"
    "Enabled=true"
    "path=/panel/desktopswitch/desktop_7"
    ""
    "[Control%2BF8.17]"
    "Comment=Switch to desktop 8"
    "Enabled=true"
    "path=/panel/desktopswitch/desktop_8"
    ""
    "[Control%2BF9.18]"
    "Comment=Switch to desktop 9"
    "Enabled=true"
    "path=/panel/desktopswitch/desktop_9"
    ""
    "[Meta%2B0.19]"
    "Comment=Activate task 10"
    "Enabled=true"
    "path=/panel/taskbar/task_10"
    ""
    "[Meta%2B1.20]"
    "Comment=Activate task 1"
    "Enabled=true"
    "path=/panel/taskbar/task_1"
    ""
    "[Meta%2B2.21]"
    "Comment=Activate task 2"
    "Enabled=true"
    "path=/panel/taskbar/task_2"
    ""
    "[Meta%2B3.22]"
    "Comment=Activate task 3"
    "Enabled=true"
    "path=/panel/taskbar/task_3"
    ""
    "[Meta%2B4.23]"
    "Comment=Activate task 4"
    "Enabled=true"
    "path=/panel/taskbar/task_4"
    ""
    "[Meta%2B5.24]"
    "Comment=Activate task 5"
    "Enabled=true"
    "path=/panel/taskbar/task_5"
    ""
    "[Meta%2B6.25]"
    "Comment=Activate task 6"
    "Enabled=true"
    "path=/panel/taskbar/task_6"
    ""
    "[Meta%2B7.26]"
    "Comment=Activate task 7"
    "Enabled=true"
    "path=/panel/taskbar/task_7"
    ""
    "[Meta%2B8.27]"
    "Comment=Activate task 8"
    "Enabled=true"
    "path=/panel/taskbar/task_8"
    ""
    "[Meta%2B9.28]"
    "Comment=Activate task 9"
    "Enabled=true"
    "path=/panel/taskbar/task_9"
    ""
    "[Print.29]"
    "Comment=Screenshot"
    "Enabled=true"
    "Exec=screengrab, -f"
    ""
    "[Shift%2BControl%2BF6.30]"
    "Comment=☀ ↓"
    "Enabled=true"
    "Exec=lxqt-config-brightness, -d"
    ""
    "[XF86MonBrightnessDown.31]"
    "Comment=☀ ↓"
    "Enabled=true"
    "Exec=lxqt-config-brightness, -d"
    ""
    "[Shift%2BControl%2BF7.32]"
    "Comment=☀ ↑"
    "Enabled=true"
    "Exec=lxqt-config-brightness, -i"
    ""
    "[XF86MonBrightnessUp.33]"
    "Comment=☀ ↑"
    "Enabled=true"
    "Exec=lxqt-config-brightness, -i"
    ""
    "[XF86AudioLowerVolume.34]"
    "Comment=Decrease sound volume"
    "Enabled=true"
    "path=/panel/volume/down"
    ""
    "[XF86AudioMute.35]"
    "Comment=Mute/unmute sound volume"
    "Enabled=true"
    "path=/panel/volume/mute"
    ""
    "[XF86AudioRaiseVolume.36]"
    "Comment=Increase sound volume"
    "Enabled=true"
    "path=/panel/volume/up"
    ""
    "[XF86Display.37]"
    "Comment=Launch Monitor"
    "Enabled=true"
    "Exec=lxqt-config-monitor"
    ""
    "[XF86Eject.38]"
    "Comment=Eject removable media"
    "Enabled=true"
    "path=/panel/mount/eject"
    ""
    "[XF86PowerOff.39]"
    "Comment=Power off key action"
    "Enabled=true"
    "path=/powermanager/keypoweroff"
    ""
    "[XF86Sleep.40]"
    "Comment=Hibernate key action"
    "Enabled=true"
    "path=/powermanager/keyhibernate"
    ""
    "[XF86Suspend.41]"
    "Comment=Suspend key action"
    "Enabled=true"
    "path=/powermanager/keysuspend"
    ""
    "[Meta%2BF11.42]"
    "Comment=QTerminal"
    "Enabled=true"
    "Exec=qterminal"
    ""
    "[Meta%2BF9.43]"
    "Comment=Run touch /tmp/kb-added"
    "Enabled=true"
    "Exec=${pkgs.writeShellScript "keybind-2" "touch /tmp/kb-added"}"
  ])}"
    "z %h/.config/lxqt/globalkeyshortcuts.conf 0644 - - -"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  environment.etc.nixos.source = "/home/kim/.config/nixos";
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
