# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/player/.config/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = "Europe/Amsterdam";

  # Profile: Gaming.
  hardware.graphics.enable = true;
  hardware.graphics.enable32Bit = true;
  programs.gamemode.enable = true;
  programs.steam.enable = true;

  # Desktop: KDE Plasma.
  services.desktopManager.plasma6.enable = true;

  # Login manager.
  services.displayManager.sddm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [
    pkgs.lutris
    pkgs.heroic
    pkgs.mangohud
    pkgs.protonup-qt
    pkgs.discord
  ];
  nixpkgs.config.allowUnfree = true;

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.player = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "battlestation";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/player/.config/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
