# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# No hardware report yet. On the machine, run
#   sudo nixos-facter -o facter.json
# here and set hardware.facter.reportPath = ./facter.json;
{ lib, ... }:
{
  # What nixos-facter detected: kernel modules, firmware, CPU microcode, …
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Driver choices.
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia.open = true;
  hardware.graphics.enable = true;
  hardware.enableRedistributableFirmware = true;
}
