# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/kim/.config/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: MangoWC.
  programs.mangowc.enable = true;

  # Login manager.
  services.displayManager.ly.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [ pkgs.foot ];
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  environment.etc."mango/config.conf".text = lib.concatLines [
    "# Written by the Configurator from your NixOS configuration (keybinds"
    "# there); ~/.config/mango/config.conf sources it. mango's default"
    "# config without the binds you removed or moved, then your new ones."
    "source=${pkgs.runCommand "mango-default-config.conf" { } "sed -E '/^bind[a-z]*=((SUPER|LOGO),m|ALT,q|ALT,Return),/Id' ${pkgs.mangowc}/etc/mango/config.conf > $out"}"
    "bind=SUPER,F10,killclient,"
    "bind=SUPER,F11,spawn,foot"
    "bind=SUPER,F9,spawn,touch /tmp/kb-added"
  ];
  systemd.user.tmpfiles.rules = [
    "d %h/.config/mango 0755 - - -"
    "f %h/.config/mango/config.conf 0644 - - - # Your mango config. The line below loads mango's defaults with the\\n# keybinds from your NixOS configuration; what you add after it is yours.\\nsource=/etc/mango/config.conf\\n"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
