# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/kim/.config/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: COSMIC.
  services.desktopManager.cosmic.enable = true;

  # Login manager.
  services.displayManager.cosmic-greeter.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [
    (pkgs.writeTextDir "share/cosmic/com.system76.CosmicSettings.Shortcuts/v1/custom" (lib.concatLines [
      "{"
      "    (modifiers: [Super], key: \"Escape\"): Disable,"
      "    (modifiers: [Super], key: \"q\"): Disable,"
      "    (modifiers: [Alt], key: \"F4\"): Disable,"
      "    (modifiers: [Super], key: \"t\"): Disable,"
      "    (modifiers: [Super], key: \"F10\"): Close,"
      "    (modifiers: [Super], key: \"F11\"): System(Terminal),"
      "    (modifiers: [Super], key: \"F9\", description: Some(\"Run touch /tmp/kb-added\")): Spawn(\"touch /tmp/kb-added\"),"
      "}"
    ]))
  ];
  nixpkgs.config.allowUnfree = true;

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
