# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/bob/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone.
  i18n.defaultLocale = "de_DE.UTF-8";
  services.xserver.xkb.layout = "de";
  console.useXkbConfig = true;
  time.timeZone = "Europe/Berlin";

  # Profile: Headless.
  services.openssh.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [ pkgs.ripgrep ];
  nixpkgs.config.allowUnfree = true;

  # Shell.
  programs.zsh.enable = true;
  users.defaultUserShell = pkgs.zsh;

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.bob = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };
  users.users.carol = {
    isNormalUser = true;
    extraGroups = [ "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "vault";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/bob/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
