# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch
# (/etc/nixos is this folder, /home/kim/.config/nixos.)
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: FVWM3.
  services.xserver.enable = true;
  services.xserver.windowManager.fvwm3.enable = true;

  # Login manager.
  services.xserver.displayManager.lightdm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  environment.etc."fvwm3/config".text = lib.concatLines [
    "# Written by the Configurator from your NixOS configuration (keybinds"
    "# there); ~/.fvwm/config reads it."
    "Read ${pkgs.fvwm3}/share/fvwm3/default-config/config"
    "Key F1 A M -"
    "Key Super_R A A -"
    "Key F11 A 4 Exec exec $[infostore.terminal]"
    "Key F9 A 4 Exec exec touch /tmp/kb-added"
  ];
  systemd.user.tmpfiles.rules = [
    "d %h/.fvwm 0755 - - -"
    "f %h/.fvwm/config 0644 - - - # Your FVWM3 config. The line below reads FVWM's default config with the\\n# keybinds from your NixOS configuration; what you add after it wins.\\nRead /etc/fvwm3/config\\n"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  environment.etc.nixos.source = "/home/kim/.config/nixos";
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
