# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/erin/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = "UTC";

  # Desktop: Sway.
  programs.sway.enable = true;

  # Login manager.
  services.displayManager.ly.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [
    pkgs.foot
    (pkgs.makeDesktopItem {
      name = "webapp-github";
      desktopName = "GitHub";
      comment = "Code hosting";
      exec = (lib.getExe pkgs.chromium + " --app=https://github.com");
      categories = [ "Network" ];
    })
  ];
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  environment.etc."sway/config.d/50-configurator-keybinds.conf".text = lib.concatLines [
    "bindsym Mod4+p exec swaymsg exit"
    ("bindsym Mod4+Return exec " + lib.getExe pkgs.foot)
    ("bindsym Mod4+Shift+g exec " + (lib.getExe pkgs.chromium + " --app=https://github.com"))
    "unbindsym Mod4+Shift+q"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.erin = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "tiles";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/erin/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
