# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch
# (/etc/nixos is this folder, /home/pat/.config/nixos.)
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (Europe/London) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_GB.UTF-8";
  services.xserver.xkb.layout = "gb";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: Openbox.
  services.xserver.enable = true;
  services.xserver.windowManager.openbox.enable = true;

  # Login manager.
  services.displayManager.ly.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [ pkgs.tint2 pkgs.obconf pkgs.thunar pkgs.alacritty ];
  nixpkgs.config.allowUnfree = true;

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.pat = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "retro";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/pat/.config/nixos" ];
  environment.etc.nixos.source = "/home/pat/.config/nixos";
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
