# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
{ ... }:
{
  # Disk layout (disko): ext4, legacy BIOS boot.
  disko.devices.disk.main = {
    type = "disk";
    device = "/dev/vdb";
    content = {
      type = "gpt";
      partitions = {
        bios = {
          size = "1M";
          type = "EF02";
        };
        boot = {
          size = "1G";
          content = {
            type = "filesystem";
            format = "ext4";
            extraArgs = [ "-O" "^metadata_csum_seed,^orphan_file,^64bit" ];
            mountpoint = "/boot";
          };
        };
        swap = {
          size = "1G";
          content = {
            type = "swap";
            randomEncryption = false;
          };
        };
        root = {
          size = "100%";
          content = {
            type = "filesystem";
            format = "ext4";
            mountpoint = "/";
          };
        };
      };
    };
  };
}
