# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/kim/.config/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: bspwm.
  services.xserver.enable = true;
  services.xserver.windowManager.bspwm.enable = true;

  # Login manager.
  services.xserver.displayManager.lightdm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [ pkgs.rxvt-unicode pkgs.dmenu ];
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  systemd.user.tmpfiles.rules = [
    "d %h/.config/sxhkd 0755 - - -"
    "C %h/.config/sxhkd/sxhkdrc - - - - ${pkgs.writeText "sxhkdrc" (lib.concatLines [
    "# From the Configurator: bspwm's example binds with your changes. Yours to edit."
    "super + Escape\n\tpkill -USR1 -x sxhkd"
    "super + alt + q\n\tbspc quit"
    "super + alt + r\n\tbspc wm -r"
    "super + shift + w\n\tbspc node -k"
    "super + m\n\tbspc desktop -l next"
    "super + y\n\tbspc node newest.marked.local -n newest.!automatic.local"
    "super + g\n\tbspc node -s biggest.window"
    "super + t\n\tbspc node -t tiled"
    "super + shift + t\n\tbspc node -t pseudo_tiled"
    "super + s\n\tbspc node -t floating"
    "super + f\n\tbspc node -t fullscreen"
    "super + ctrl + m\n\tbspc node -g marked"
    "super + ctrl + x\n\tbspc node -g locked"
    "super + ctrl + y\n\tbspc node -g sticky"
    "super + ctrl + z\n\tbspc node -g private"
    "super + h\n\tbspc node -f west"
    "super + j\n\tbspc node -f south"
    "super + k\n\tbspc node -f north"
    "super + l\n\tbspc node -f east"
    "super + shift + h\n\tbspc node -s west"
    "super + shift + j\n\tbspc node -s south"
    "super + shift + k\n\tbspc node -s north"
    "super + shift + l\n\tbspc node -s east"
    "super + p\n\tbspc node -f @parent"
    "super + b\n\tbspc node -f @brother"
    "super + comma\n\tbspc node -f @first"
    "super + period\n\tbspc node -f @second"
    "super + c\n\tbspc node -f next.local.!hidden.window"
    "super + shift + c\n\tbspc node -f prev.local.!hidden.window"
    "super + bracketleft\n\tbspc desktop -f prev.local"
    "super + bracketright\n\tbspc desktop -f next.local"
    "super + grave\n\tbspc node -f last"
    "super + Tab\n\tbspc desktop -f last"
    "super + o\n\tbspc wm -h off; bspc node older -f; bspc wm -h on"
    "super + i\n\tbspc wm -h off; bspc node newer -f; bspc wm -h on"
    "super + 1\n\tbspc desktop -f '^1'"
    "super + 2\n\tbspc desktop -f '^2'"
    "super + 3\n\tbspc desktop -f '^3'"
    "super + 4\n\tbspc desktop -f '^4'"
    "super + 5\n\tbspc desktop -f '^5'"
    "super + 6\n\tbspc desktop -f '^6'"
    "super + 7\n\tbspc desktop -f '^7'"
    "super + 8\n\tbspc desktop -f '^8'"
    "super + 9\n\tbspc desktop -f '^9'"
    "super + 0\n\tbspc desktop -f '^10'"
    "super + shift + 1\n\tbspc node -d '^1'"
    "super + shift + 2\n\tbspc node -d '^2'"
    "super + shift + 3\n\tbspc node -d '^3'"
    "super + shift + 4\n\tbspc node -d '^4'"
    "super + shift + 5\n\tbspc node -d '^5'"
    "super + shift + 6\n\tbspc node -d '^6'"
    "super + shift + 7\n\tbspc node -d '^7'"
    "super + shift + 8\n\tbspc node -d '^8'"
    "super + shift + 9\n\tbspc node -d '^9'"
    "super + shift + 0\n\tbspc node -d '^10'"
    "super + ctrl + h\n\tbspc node -p west"
    "super + ctrl + j\n\tbspc node -p south"
    "super + ctrl + k\n\tbspc node -p north"
    "super + ctrl + l\n\tbspc node -p east"
    "super + ctrl + 1\n\tbspc node -o 0.1"
    "super + ctrl + 2\n\tbspc node -o 0.2"
    "super + ctrl + 3\n\tbspc node -o 0.3"
    "super + ctrl + 4\n\tbspc node -o 0.4"
    "super + ctrl + 5\n\tbspc node -o 0.5"
    "super + ctrl + 6\n\tbspc node -o 0.6"
    "super + ctrl + 7\n\tbspc node -o 0.7"
    "super + ctrl + 8\n\tbspc node -o 0.8"
    "super + ctrl + 9\n\tbspc node -o 0.9"
    "super + ctrl + space\n\tbspc node -p cancel"
    "super + ctrl + shift + space\n\tbspc query -N -d | xargs -I id -n 1 bspc node id -p cancel"
    "super + alt + h\n\tbspc node -z left -20 0"
    "super + alt + j\n\tbspc node -z bottom 0 20"
    "super + alt + k\n\tbspc node -z top 0 -20"
    "super + alt + l\n\tbspc node -z right 20 0"
    "super + alt + shift + h\n\tbspc node -z right -20 0"
    "super + alt + shift + j\n\tbspc node -z top 0 20"
    "super + alt + shift + k\n\tbspc node -z bottom 0 -20"
    "super + alt + shift + l\n\tbspc node -z left 20 0"
    "super + Left\n\tbspc node -v -20 0"
    "super + Down\n\tbspc node -v 0 20"
    "super + Up\n\tbspc node -v 0 -20"
    "super + Right\n\tbspc node -v 20 0"
    "super + F10\n\tbspc node -c"
    "super + F11\n\turxvt"
    "super + F9\n\ttouch /tmp/kb-added"
  ])}"
    "z %h/.config/sxhkd/sxhkdrc 0644 - - -"
    "d %h/.config/bspwm 0755 - - -"
    "C %h/.config/bspwm/bspwmrc - - - - ${pkgs.bspwm + "/share/doc/bspwm/examples/bspwmrc"}"
    "z %h/.config/bspwm/bspwmrc 0755 - - -"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
