# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch
# (/etc/nixos is this folder, /home/kim/.config/nixos.)
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: Hyprland.
  programs.hyprland.enable = true;

  # Login manager.
  services.displayManager.sddm.enable = true;
  services.displayManager.sddm.wayland.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [ pkgs.kitty ];
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  environment.etc."xdg/hypr/configurator.lua".text = lib.concatLines [
    "-- Written by the Configurator from your NixOS configuration (keybinds"
    "-- there); ~/.config/hypr/hyprland.lua loads it. Hyprland's defaults,"
    "-- then your changes to them."
    "dofile(\"${pkgs.hyprland}/share/hypr/hyprland.lua\")"
    "hl.unbind(\"SUPER + e\")"
    "hl.unbind(\"SUPER + c\")"
    "hl.unbind(\"SUPER + q\")"
    "hl.bind(\"SUPER + F10\", hl.dsp.window.close())"
    "hl.bind(\"SUPER + F11\", hl.dsp.exec_cmd(\"kitty\"))"
    "hl.bind(\"SUPER + F9\", hl.dsp.exec_cmd(\"touch /tmp/kb-added\"))"
  ];
  systemd.user.tmpfiles.rules = [
    "d %h/.config/hypr 0755 - - -"
    "f %h/.config/hypr/hyprland.lua 0644 - - - -- Your Hyprland config. The first line loads Hyprland's defaults with the\\n-- keybinds from your NixOS configuration; everything after it is yours\\n-- (monitors, input, more binds: https://wiki.hypr.land/Configuring/).\\ndofile(\"/etc/xdg/hypr/configurator.lua\")\\n"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  environment.etc.nixos.source = "/home/kim/.config/nixos";
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
