# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/kim/.config/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: evilwm.
  fonts.packages = ([ (pkgs.runCommand "x11-font-aliases" { } "mkdir -p $out/share/fonts/X11/misc && cp ${pkgs.font-alias}/share/fonts/X11/misc/fonts.alias $out/share/fonts/X11/misc && echo 0 > $out/share/fonts/X11/misc/fonts.dir") ]);
  services.xserver.enable = true;
  services.xserver.windowManager.evilwm.enable = true;

  # Login manager.
  services.xserver.displayManager.lightdm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  systemd.user.tmpfiles.rules = [
    "f %h/.evilwmrc 0644 - - - # Your evilwm options, on top of its built-in binds. The Configurator\\n# started it with the keybinds you chose; see evilwm(1).\\nbind control+mod1+k\\nbind control+mod1+Escape\\nbind control+mod1+Return\\nbind mod4+F10=delete\\nbind mod4+F11=spawn\\n"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
