# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/kim/.config/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: niri.
  programs.niri.enable = true;

  # Login manager.
  services.displayManager.ly.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [ pkgs.alacritty pkgs.fuzzel ];
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  environment.etc."niri/config.kdl".text = lib.concatLines [
    "// Written by the Configurator from your NixOS configuration (keybinds"
    "// there); ~/.config/niri/config.kdl includes it. niri's default config"
    "// without the binds you removed or moved, then your new ones."
    "include \"${pkgs.runCommand "niri-default-config.kdl" { } "sed -E '/^binds \\{/,/^\\}/{/^\\s*((Mod|Super)\\+d|(Mod|Super)\\+q|(Mod|Super)\\+t)(\\s|\\{)/Id}' ${pkgs.niri.src}/resources/default-config.kdl > $out"}\""
    "binds {"
    "    Mod+F10 { close-window; }"
    "    Mod+F11 { spawn \"alacritty\"; }"
    "    Mod+F9 { spawn-sh \"touch /tmp/kb-added\"; }"
    "}"
  ];
  systemd.user.tmpfiles.rules = [
    "d %h/.config/niri 0755 - - -"
    "f %h/.config/niri/config.kdl 0644 - - - // Your niri config: outputs, input, layout, more binds\\n// (https://github.com/YaLTeR/niri/wiki/Configuration:-Introduction).\\n// The line below loads niri's defaults with the keybinds from your NixOS\\n// configuration; what you write after it wins.\\ninclude \"/etc/niri/config.kdl\"\\n"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
