# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/me/.config/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = "Europe/Amsterdam";

  # Desktop: Omarchy.
  omarchy.configDir = "/home/me/.config/nixos";
  omarchy.enable = true;
  omarchy.stateDir = ./omarchy;
  omarchy.users = [ "me" ];
  omarchy.ecosystem.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [
    pkgs.wireshark
    pkgs.spotify
    pkgs.gh
    pkgs.gemini-cli
    (pkgs.makeDesktopItem {
      name = "webapp-slack";
      desktopName = "Slack";
      comment = "Team chat";
      exec = (lib.getExe pkgs.chromium + " --app=https://app.slack.com/client");
      categories = [ "Network" ];
    })
  ];
  nixpkgs.config.allowUnfree = true;
  home-manager.users.me.omarchy.agents = [ "claude" ];
  home-manager.users.me.omarchy.defaultAgent = "claude";
  home-manager.users.me.omarchy.apps = {
    enable = true;
    picks = [
      "aether"
      "herdr"
      "omacalc"
      "omacut"
      "omawrite"
      "spotify"
      "tobi-try"
    ];
  };
  home-manager.users.me.omarchy.cli.inxi.enable = false;
  home-manager.users.me.omarchy.webapps = {
    enable = true;
    picks = [ "youtube" "hey" ];
  };

  # Development. Start a project from a template with:
  #   nix flake new -t dev#go ~/Projects/my-go-project
  programs.direnv.enable = true;
  nix.registry.dev.to = {
    type = "github";
    owner = "nix-templates";
    repo = "dev";
  };
  virtualisation.docker.enable = true;
  virtualisation.oci-containers.backend = "docker";
  virtualisation.oci-containers.containers.minio = {
    image = "minio/minio:latest";
    ports = [ "127.0.0.1:9000:9000" "127.0.0.1:9001:9001" ];
    environment = {
      MINIO_ROOT_PASSWORD = "minioadmin";
      MINIO_ROOT_USER = "minioadmin";
    };
    volumes = [ "minio:/data" ];
    cmd = [ "server" "/data" "--console-address" ":9001" ];
  };

  # Shell.
  programs.zsh.enable = true;
  users.defaultUserShell = pkgs.zsh;

  # Keybinds, on top of the desktop's defaults.
  home-manager.users.me.omarchy.keybinds = {
    "SUPER + SHIFT + K" = {
      exec = (lib.getExe pkgs.chromium + " --app=https://app.slack.com/client");
    };
    "SUPER + SHIFT + M" = {
      launch = "spotify";
    };
    "SUPER + SHIFT + N" = {
      enable = false;
    };
    "SUPER + SHIFT + W" = {
      exec = "wireshark";
    };
  };

  # Boot and security.
  boot.loader.systemd-boot.enable = lib.mkForce false;
  boot.lanzaboote.enable = true;
  boot.lanzaboote.pkiBundle = "/var/lib/sbctl";
  boot.loader.efi.canTouchEfiVariables = true;
  configurator.tpmPin.enable = true;

  # Users. Passwords are set during install, not stored here.
  users.users.me = {
    isNormalUser = true;
    description = "Me Myself";
    extraGroups = [ "wheel" "networkmanager" "video" "docker" ];
  };
  home-manager.useGlobalPkgs = true;
  home-manager.useUserPackages = true;
  home-manager.users.me.home.stateVersion = "26.05";

  # System.
  networking.hostName = "omarchy";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/me/.config/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
