[package]
name = "configurator-gtk"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
adw = { version = "0.9.2", package = "libadwaita", features = ["v1_7"] }
configurator-answers.workspace = true
configurator-catalog.workspace = true
configurator-engine.workspace = true
configurator-flakegen.workspace = true
gtk = { version = "0.11.5", package = "gtk4", features = ["v4_18"] }
