# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/kim/.config/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: i3.
  services.xserver.enable = true;
  services.xserver.windowManager.i3.enable = true;

  # Login manager.
  services.xserver.displayManager.lightdm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  environment.etc."xdg/i3/config".text = lib.concatLines [
    "# Written by the Configurator from your NixOS configuration (keybinds"
    "# there). i3's default config without the binds you removed or moved,"
    "# then your new ones. A ~/.config/i3/config of your own replaces all"
    "# of it; binds in ~/.config/i3/config.d/ come on top."
    "include ${pkgs.runCommand "i3-default-config" { } "sed -E '/i3-config-wizard/d; /^bindsym/{s/\\$left/j/;s/\\$down/k/;s/\\$up/l/;s/\\$right/semicolon/}; /^bindsym ((Mod1|Alt)\\+d|(Mod1|Alt)\\+Shift\\+q|Shift\\+(Mod1|Alt)\\+q|(Mod1|Alt)\\+Return)\\s/Id' ${pkgs.i3}/etc/i3/config > $out"}"
    "bindsym Mod4+F10 kill"
    "bindsym Mod4+F11 exec i3-sensible-terminal"
    "bindsym Mod4+F9 exec --no-startup-id \"touch /tmp/kb-added\""
    "include ~/.config/i3/config.d/*"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
