# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/kim/.config/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: Openbox.
  services.xserver.enable = true;
  services.xserver.windowManager.openbox.enable = true;

  # Login manager.
  services.xserver.displayManager.lightdm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [ pkgs.xterm ];
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  environment.etc."xdg/openbox/rc.xml".source = pkgs.runCommand "openbox-rc.xml" {
    binds = lib.concatLines [
      "    <keybind key=\"W-F10\"><action name=\"Close\" /></keybind>"
      "    <keybind key=\"W-F9\"><action name=\"Execute\"><command>touch /tmp/kb-added</command></action></keybind>"
    ];
    passAsFile = [ "binds" ];
    nativeBuildInputs = [ pkgs.perl ];
  } "cp ${pkgs.openbox}/etc/xdg/openbox/rc.xml $out\nchmod +w $out\nperl -0pi -e 's{\\s*<keybind key=\"(?:A-space|A-F4)\">.*?</keybind>}{}gs' $out\nsed -i \"/<\\/keyboard>/e cat $bindsPath\" $out\n";

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
