# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch
# (/etc/nixos is this folder, /home/kim/.config/nixos.)
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: river.
  programs.river-classic.enable = true;

  # Login manager.
  services.displayManager.ly.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  environment.etc."river/init" = {
    text = lib.concatLines [
      "#!/bin/sh"
      "# Written by the Configurator from your NixOS configuration (keybinds"
      "# there); ~/.config/river/init runs it. river's example init, then your"
      "# changes to its binds."
      ". ${pkgs.river-classic}/example/init"
      "riverctl unmap normal Super+Shift e"
      "riverctl unmap normal Super q"
      "riverctl unmap normal Super+Shift Return"
      "riverctl map normal Super F10 close"
      "riverctl map normal Super F11 spawn foot"
      "riverctl map normal Super F9 spawn 'touch /tmp/kb-added'"
    ];
    mode = "0755";
  };
  systemd.user.tmpfiles.rules = [
    "d %h/.config/river 0755 - - -"
    "f %h/.config/river/init 0755 - - - #!/bin/sh\\n# Your river config. The line below runs river's example init with the\\n# keybinds from your NixOS configuration; add your own riverctl commands\\n# after it (see riverctl(1)).\\n. /etc/river/init\\n"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  environment.etc.nixos.source = "/home/kim/.config/nixos";
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
