# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch
# (/etc/nixos is this folder, /home/omar/.config/nixos.)
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (Europe/Amsterdam) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: Omarchy.
  omarchy.configDir = "/home/omar/.config/nixos";
  omarchy.enable = true;
  omarchy.stateDir = ./omarchy;
  omarchy.users = [ "omar" ];
  nix.settings.extra-substituters = [ "https://nix-desktops.cachix.org" ];
  nix.settings.extra-trusted-public-keys = [
    "nix-desktops.cachix.org-1:3nwBByDXptI8ugWCbaSjfrXmqa8+Fo9UUvwCZX5IPeA="
  ];
  nix.settings.fallback = true;
  nix.settings.connect-timeout = 10;

  # Apps, web apps, AI agents and command-line tools.
  nixpkgs.config.allowUnfree = true;
  home-manager.users.omar.omarchy.agents = [ "claude" ];
  home-manager.users.omar.omarchy.defaultAgent = "claude";
  home-manager.users.omar.omarchy.webapps = {
    enable = true;
    picks = [ "youtube" ];
  };

  # Shell.
  omarchy.shell = "zsh";
  programs.zsh.enable = true;
  users.defaultUserShell = pkgs.zsh;

  # Keybinds, on top of the desktop's defaults.
  home-manager.users.omar.omarchy.keybinds = {
    "SUPER + SHIFT + Y" = {
      webapp = "youtube";
    };
  };

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.omar = {
    isNormalUser = true;
    description = "Omar Chy";
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };
  home-manager.useGlobalPkgs = true;
  home-manager.useUserPackages = true;
  home-manager.users.omar.home.stateVersion = "26.05";

  # System.
  networking.hostName = "omarchy";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/omar/.config/nixos" ];
  environment.etc.nixos.source = "/home/omar/.config/nixos";
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
