# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/kim/.config/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: IceWM.
  services.xserver.enable = true;
  services.xserver.windowManager.icewm.enable = true;

  # Login manager.
  services.xserver.displayManager.lightdm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  environment.etc."icewm/preferences".text = lib.concatLines [
    "# Written by the Configurator from your NixOS configuration (keybinds there)."
    "# Super binds window actions, so the Super key alone doesn't open the menu (Ctrl+Esc does)."
    "Win95Keys=0"
    "KeyWinClose=\"Super+F10\""
  ];
  environment.etc."icewm/keys".source = pkgs.runCommand "icewm-keys" {
    binds = lib.concatLines [
      "key \"Super+F11\" xterm"
      "key \"Super+F9\" touch /tmp/kb-added"
    ];
    passAsFile = [ "binds" ];
  } "cp ${pkgs.icewm}/share/icewm/keys $out\nchmod +w $out\nsed -Ei '/^(switch)?key \"(Ctrl\\+Alt\\+b|Alt\\+Ctrl\\+b|Ctrl\\+Alt\\+t|Alt\\+Ctrl\\+t)\"/Id' $out\ncat $bindsPath >> $out\n";

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
