# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/kim/.config/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: Fluxbox.
  services.xserver.enable = true;
  services.xserver.windowManager.fluxbox.enable = true;

  # Login manager.
  services.xserver.displayManager.lightdm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  systemd.user.tmpfiles.rules = [
    "d %h/.fluxbox 0755 - - -"
    "C %h/.fluxbox/keys - - - - ${pkgs.runCommand "fluxbox-keys" {
    binds = lib.concatLines [
      "Mod4 F10 :Close"
      "Mod4 F11 :Exec xterm"
      "Mod4 F9 :Exec touch /tmp/kb-added"
    ];
    passAsFile = [ "binds" ];
  } "cp ${pkgs.fluxbox}/share/fluxbox/keys $out\nchmod +w $out\nsed -Ei '/^(Mod1 +F2|Mod1 +F4|Mod1 +F1|Mod4 +F10|Mod4 +F11|Mod4 +F9) +:/Id' $out\ncat $bindsPath >> $out\n"}"
    "z %h/.fluxbox/keys 0644 - - -"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
