# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/kim/.config/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: Xfce.
  services.xserver.desktopManager.xfce.enable = true;
  services.xserver.enable = true;

  # Login manager.
  services.xserver.displayManager.lightdm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  environment.etc."xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml".text = lib.concatLines [
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
    "<channel name=\"xfce4-keyboard-shortcuts\" version=\"1.0\">"
    "  <property name=\"commands\" type=\"empty\">"
    "    <property name=\"default\" type=\"empty\">"
    "      <property name=\"&lt;Primary&gt;&lt;Alt&gt;Escape\" type=\"empty\"><property name=\"startup-notify\" type=\"empty\"/></property>"
    "      <property name=\"&lt;Primary&gt;&lt;Alt&gt;t\" type=\"empty\"><property name=\"startup-notify\" type=\"empty\"/></property>"
    "      <property name=\"&lt;Super&gt;F11\" type=\"string\" value=\"exo-open --launch TerminalEmulator\"/>"
    "      <property name=\"&lt;Super&gt;F9\" type=\"string\" value=\"touch /tmp/kb-added\"/>"
    "    </property>"
    "  </property>"
    "  <property name=\"xfwm4\" type=\"empty\">"
    "    <property name=\"default\" type=\"empty\">"
    "      <property name=\"&lt;Alt&gt;F4\" type=\"empty\"/>"
    "      <property name=\"&lt;Super&gt;F10\" type=\"string\" value=\"close_window_key\"/>"
    "    </property>"
    "  </property>"
    "</channel>"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
