# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/omar/.config/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: Omarchy.
  omarchy.configDir = "/home/omar/.config/nixos";
  omarchy.enable = true;
  omarchy.stateDir = ./omarchy;
  omarchy.users = [ "omar" ];
  nix.settings.extra-substituters = [ "https://nix-desktops.cachix.org" ];
  nix.settings.extra-trusted-public-keys = [
    "nix-desktops.cachix.org-1:3nwBByDXptI8ugWCbaSjfrXmqa8+Fo9UUvwCZX5IPeA="
  ];
  nix.settings.fallback = true;
  nix.settings.connect-timeout = 10;

  # Apps, web apps, AI agents and command-line tools.
  nixpkgs.config.allowUnfree = true;

  # Shell.
  omarchy.shell = "bash";

  # Keybinds, on top of the desktop's defaults.
  home-manager.users.omar.omarchy.keybinds = {
    "SUPER + F10" = {
      description = "Close window";
      lua = "hl.dsp.window.close()";
    };
    "SUPER + F11" = {
      description = "Terminal";
      omarchy = "terminal";
    };
    "SUPER + F12" = {
      description = "Mute";
      exec = "omarchy-audio-output-volume mute-toggle";
      locked = true;
    };
    "SUPER + F9" = {
      exec = "touch /tmp/kb-added";
    };
    "SUPER + RETURN" = {
      enable = false;
    };
    "SUPER + SHIFT + N" = {
      enable = false;
    };
    "SUPER + W" = {
      enable = false;
    };
    XF86AudioMute = {
      enable = false;
    };
  };

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.omar = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };
  home-manager.useGlobalPkgs = true;
  home-manager.useUserPackages = true;
  home-manager.users.omar.home.stateVersion = "26.05";

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/omar/.config/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
