# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Apply changes with: sudo nixos-rebuild switch
# (/etc/nixos is this folder, /home/omar/.config/nixos.)
{
  description = "NixOS configuration of keys";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    home-manager = {
      url = "github:nix-community/home-manager/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    omarchy = {
      url = "github:nix-desktops/omarchy/stable";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.home-manager.follows = "home-manager";
    };
  };
  outputs = { nixpkgs, ... }@inputs: {
    nixosConfigurations.keys = nixpkgs.lib.nixosSystem {
      specialArgs = { inherit inputs; };
      modules = [
        inputs.disko.nixosModules.disko
        inputs.home-manager.nixosModules.home-manager
        inputs.omarchy.nixosModules.default
        ./disko.nix
        ./hardware.nix
        ./configuration.nix
      ];
    };
  };
}
