# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/kim/.config/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: Wayfire.
  programs.wayfire.enable = true;

  # Login manager.
  services.displayManager.ly.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [ pkgs.foot ];
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  environment.etc."wayfire/defaults.ini".text = lib.concatLines [
    "# Written by the Configurator from your NixOS configuration (keybinds"
    "# there): Wayfire's defaults, which your ~/.config/wayfire.ini overrides."
    "[core]"
    "close_top_view = <super> KEY_F10"
    "[expo]"
    "toggle = none"
  ];
  systemd.user.tmpfiles.rules = [
    "d %h/.config 0755 - - -"
    "f %h/.config/wayfire.ini 0644 - - - # Your Wayfire config (Wayfire Config Manager edits it too). The commands\\n# below came from the Configurator; /etc/wayfire/defaults.ini has the rest\\n# of your NixOS configuration's keybinds.\\n[command]\\nbinding_configurator0 = <super> KEY_F9\\ncommand_configurator0 = touch /tmp/kb-added\\n"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
