# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
{ ... }:
{
  # Disk layout (disko): ext4.
  disko.devices.disk.main = {
    type = "disk";
    device = "/dev/vdb";
    content = {
      type = "gpt";
      partitions = {
        ESP = {
          size = "1G";
          type = "EF00";
          content = {
            type = "filesystem";
            format = "vfat";
            mountpoint = "/boot";
            mountOptions = [ "umask=0077" ];
          };
        };
        root = {
          size = "100%";
          content = {
            type = "filesystem";
            format = "ext4";
            mountpoint = "/";
          };
        };
      };
    };
  };
}
