# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch --flake /home/kim/.config/nixos
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: labwc.
  programs.labwc.enable = true;

  # Login manager.
  services.displayManager.ly.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [ pkgs.foot ];
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  environment.etc."xdg/labwc/rc.xml".text = lib.concatLines [
    "<?xml version=\"1.0\"?>"
    "<!-- Written by the Configurator from your NixOS configuration (keybinds"
    "     there). Your own ~/.config/labwc/rc.xml comes on top of it. -->"
    "<labwc_config>"
    "  <keyboard>"
    "    <default />"
    "    <keybind key=\"W-a\"><action name=\"None\" /></keybind>"
    "    <keybind key=\"A-F4\"><action name=\"None\" /></keybind>"
    "    <keybind key=\"W-Return\"><action name=\"None\" /></keybind>"
    "    <keybind key=\"W-F10\"><action name=\"Close\" /></keybind>"
    "    <keybind key=\"W-F11\"><action name=\"Execute\" command=\"lab-sensible-terminal\" /></keybind>"
    "    <keybind key=\"W-F9\"><action name=\"Execute\" command=\"touch /tmp/kb-added\" /></keybind>"
    "  </keyboard>"
    "</labwc_config>"
  ];
  programs.labwc.package = pkgs.symlinkJoin {
    name = "labwc-merge-config";
    paths = [ pkgs.labwc ];
    nativeBuildInputs = [ pkgs.makeWrapper ];
    # The user's rc.xml adds to /etc/xdg/labwc/rc.xml.
    postBuild = "wrapProgram $out/bin/labwc --add-flags --merge-config";
    passthru.providedSessions = [ "labwc" ];
  };

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
