# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch
# (/etc/nixos is this folder, /home/kim/.config/nixos.)
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: herbstluftwm.
  services.xserver.enable = true;
  services.xserver.windowManager.herbstluftwm.enable = true;

  # Login manager.
  services.xserver.displayManager.lightdm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  environment.etc."herbstluftwm/autostart" = {
    text = lib.concatLines [
      "#!/bin/sh"
      "# Written by the Configurator from your NixOS configuration (keybinds"
      "# there); ~/.config/herbstluftwm/autostart runs it."
      "${pkgs.herbstluftwm}/etc/xdg/herbstluftwm/autostart"
      "herbstclient keyunbind Mod1-Shift-q"
      "herbstclient keyunbind Mod1-Shift-c"
      "herbstclient keyunbind Mod1-Return"
      "herbstclient keybind Mod4-F10 close"
      "herbstclient keybind Mod4-F11 spawn \"\${TERMINAL:-xterm}\""
      "herbstclient keybind Mod4-F9 spawn sh -c 'touch /tmp/kb-added'"
    ];
    mode = "0755";
  };
  systemd.user.tmpfiles.rules = [
    "d %h/.config/herbstluftwm 0755 - - -"
    "f %h/.config/herbstluftwm/autostart 0755 - - - #!/bin/sh\\n# Your herbstluftwm autostart. The line below runs herbstluftwm's own with\\n# the keybinds from your NixOS configuration; add your commands after it.\\n/etc/herbstluftwm/autostart\\n"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  environment.etc.nixos.source = "/home/kim/.config/nixos";
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
