# Generated by the Configurator (github:nix-composer/configurator).
# This is your system now: edit it freely.
# Your choices, one section per installer layer. Apply changes with:
#   sudo nixos-rebuild switch
# (/etc/nixos is this folder, /home/kim/.config/nixos.)
{ lib, pkgs, ... }:
{
  # Basics: language, keyboard and time zone. The time zone (UTC) was set
  # during the install and is yours to change (your desktop's settings or
  # `timedatectl set-timezone`); set time.timeZone to fix it here instead.
  i18n.defaultLocale = "en_US.UTF-8";
  services.xserver.xkb.layout = "us";
  console.useXkbConfig = true;
  time.timeZone = null;

  # Desktop: KDE Plasma.
  services.desktopManager.plasma6.enable = true;

  # Login manager.
  services.displayManager.sddm.enable = true;

  # Apps, web apps, AI agents and command-line tools.
  environment.systemPackages = [
    (pkgs.makeDesktopItem {
      name = "configurator-keybind-1";
      desktopName = "Run touch /tmp/kb-added";
      exec = "${pkgs.writeShellScript "keybind-1" "touch /tmp/kb-added"}";
      noDisplay = true;
    })
  ];
  nixpkgs.config.allowUnfree = true;

  # Keybinds, on top of the desktop's defaults.
  systemd.user.tmpfiles.rules = [
    "d %h/.config 0755 - - -"
    "f %h/.config/kglobalshortcutsrc 0600 - - - [kwin]\\nExpose=Ctrl+F9,,\\nExposeAll=LaunchC\\\\tCtrl+F10,,\\nWindow Close=Meta+F10,,\\n[services][configurator-keybind-1.desktop]\\n_launch=Meta+F9\\n[services][org.kde.dolphin.desktop]\\n_launch=none\\n[services][org.kde.konsole.desktop]\\n_launch=Meta+F11\\n"
  ];

  # Boot and security.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Users. Passwords are set during install, not stored here.
  users.users.kim = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  # System.
  networking.hostName = "keys";
  networking.networkmanager.enable = true;
  programs.git.enable = true;
  programs.git.config.safe.directory = [ "/home/kim/.config/nixos" ];
  environment.etc.nixos.source = "/home/kim/.config/nixos";
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";
}
